.editorconfig

This is the default whitespace style used in VS

Add .csproj rule to .editorconfig

---

README.md

We also don't need any token anymore.

README: update travis-link to travis-ci.org

---

src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/EntityTypes/MemberBuilder.cs
src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/Naming/Naming.cs
src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/Syntax/SyntaxGenerator.cs

It seems this generator is written without concern for arrays of
arrays, which we use in our API.
According to the docs-team, this was ad-hoc hacked around when
outputting the API in the past. But let's instead do this correctly,
by peeling away multiple arrays rather than just a single one.
This prevents an error about missing namespace for `byte[]` when
updating API docs.

UnoDoc: handle arrays of arrays

---

src/ux/Uno.UX.Markup.AST/Tests/Uno.UX.Markup.AST.Tests.csproj
src/ux/Uno.UX.Markup.AST/Uno.UX.Markup.AST.csproj
src/ux/Uno.UX.Markup.Common/Uno.UX.Markup.Common.csproj

This is not named System.XML, as we used here. This worked without
this patch, because we only build on Windows and case-insensitive
HFS+ currently.
This patch opens the door for case-sensitive HFS+, as well as Linux.

Uno.UX.Markup.*: fix casing of System.Xml

---

Library/Core/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist

By default, UIBackground modes on iOS project doesn't contains any value which will need extra work and time from the developer like below.
Every time he would likes to run the project on his mobile he need t check that option like the image each time.
I have make it added automatically once the `Unoproj` file contains the `Push` capability it directly added to project `.plist` file.
Also, the file contained multiple definitions for the UIBackgroundModes and not listed on the Documentations you have i have wrapped them into one plist `array` to mitigate any conflicts on the proejct files.

Enable Remote Notifications mode on Background Modes in Plist file while enabling push notifications

---

src/compiler/Uno.Compiler.Core/Syntax/UxlProcessor.cs

Fix App Store issue while uploading the app to App Store because of App Icon has invalid format and they have to be stripped from alpha channel.
The previous image was generated using default settings of .NET graphics. I have fixed it and adding additional app icon sizes by simply setting `CompositingMode` attribute for .NET graphics to `CompositingMode.SourceOver`
for further information see this example of XCode error message after archiving the App
Also it's listed here in Apple's guidelines for [Human Interface Guidelines ](https://developer.apple.com/ios/human-interface-guidelines/icons-and-images/app-icon/):
> Keep the background simple and avoid transparency. Make sure your icon is opaque, and don’t clutter the background. Give it a simple background so it doesn’t overpower other …

Fix App Store issue while uploading the app to App Store because of App Icons are invalid format 

---

Library/Core/Uno.Permissions/Permissions.java

I have reformated the braces and fixed the `NullPointerException` crash by copying the condition used on `nextRequest()` method.
I figured it out by using `Firabase Crashlytics` and it says that there is a crash with the following information: 
```
Caused by java.lang.NullPointerException
Attempt to read from field 'int com.fuse.PermissionsRequest.requestID' on a null object reference
```
```
com.fuse.Permissions.onRequestPermissionsResult (Permissions.java:80)
```
Best Regards.

Fix android permissions crash while _currentRequest is null

---

src/compiler/Uno.Compiler.Core/IL/Validation/ILAnalyzer.cs

Only report warning when parameter types are the same as the declaring type.
This removes warnings when building the standard library, i.e.:
W0000: Uno.Data.Xml.XmlValue defines operator == or operator != but does not override object.Equals(object o)
W0000: Uno.Data.Xml.XmlValue defines operator == or operator != but does not override object.GetHashCode()

Uno.Compiler: don't report false warnings on equality operators

---

src/main/Uno.CLI/Android/LaunchApk.cs

Sometimes we get exceptions inside the timers, and we don't want our program to
get stuck..
Specifically, I just got an exception from AdbDevice.GetProcessId().

Uno.CLI: catch exceptions to avoid hanging in LaunchApk

---

src/compiler/Uno.Compiler.Frontend/Preprocessor/Preprocessor.cs

This avoids false calls to `Log.Error()`, which is a convenient place to set
breakpoints. So, let's make life a little bit easier when debugging the
compiler..

Uno.Compiler.Frontend: early-out in TryParseCondition()

---

src/compiler/Uno.Compiler.Core/IL/Bytecode/BytecodeCompiler.Expression.cs
tests/src/UnoTest/Mono/_ignore.txt
tests/src/UnoTest/Mono/test-487.uno

We now correctly compile expressions such as '&(this = x)' (pseudo code).
This avoids getting Assertion Failed from IKVM.Reflection during compilation
of UnoTest.
Minimal repro:
struct X
{
int i;
int f()
{
return (this = default(X)).i;
}
}

Uno.Compiler: fix stack underflow in BytecodeCompiler

---

Library/Core/UnoCore/Source/OpenGL/GL.uno
src/compiler/Uno.Compiler.API/Backends/FunctionOptions.cs
src/compiler/Uno.Compiler.Backends.CIL/CilBackend.cs
src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.Expression.cs
src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.Statement.cs

If we try to compile 'extern' code on .NET we'll get exceptions in `CilBackend`, i.e.:
```
void foo()
@{
// code here
@}
```
These errors are hard to fix because the compiler doesn't give us any source information.
After this fix, we get a more helpful error message that tells us where to fix the problem.

Uno.Compiler: report error on unsupported 'extern' code

---

Library/Core/UnoCore/Source/Uno/Runtime/Implementation/Internal/Bootstrapper.uno
src/compiler/Uno.Compiler.Backends.CSharp/CsBackend.GenerateProject.cs
src/compiler/Uno.Compiler.Backends.CSharp/CsWriter.cs
src/runtime/Uno.Runtime.Core/OpenGL/GL.cs
src/runtime/Uno.Runtime.Core/Uno.Runtime.Core.csproj
src/runtime/Uno.Runtime.Core/Uno/Application.cs

Re-generating UnoCore is not currently possible, due to a few mismatches between the current sources and the generator. This isn't ideal, as it means people will have to carefully stage only the changes they want.
This series have two small fixes "tacked on", but they are all kinda related:
- The FirefoxOS-define is never defined any more, so checking for it is kinda pointless.
- The C# writer now emits `new`-keywords for definitions that previously missed them. This eliminates a compile-time warning.

Fixup UnoCore generation

---

Library/Core/UnoCore/Targets/Android/app/build.gradle

Hello!
Android O is here and dependencies versions must be updated in order to be able to utilize API 26 new features 
This is a simple pull requests that made the change of support libraries to `26.0.2` and added google maven repository in order to be able to fetch the new support libraries
That's all,
Thanks

Update android app gradle dependency Libraries

---

src/compiler/Uno.Compiler.Backends.CPlusPlus/CppWriter.cs
tests/src/UnoTest/General/ValueTypes.uno

This adds a new test based on a fail-case from fuselibs, and add stack-boxing
when emitting virtual calls on value types in CppWriter.WriteMemberBase().
Before this patch, we got C++ compile errors when building fuselibs.

Uno.Compiler: fix C++ regression after #48

---

src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.Statement.cs

This fixes build errors when building fuselibs.

ILVerifier: check foreign attribute in VerifyExtern()

---

Library/Core/UnoCore/Targets/Android/app/build.gradle

Otherwise we'll get these build errors (regression from #57):
> Could not find com.android.support:appcompat-v7:26.0.2.
Required by:
Debug:app:unspecified
> Could not find com.android.support:design:26.0.2.
Required by:
Debug:app:unspecified

Android: the maven repository is always required

---

Library/Core/UnoCore/Targets/Android/Android.uxl
Library/Core/UnoCore/Targets/Android/app/build.gradle
Library/Core/UnoCore/Targets/Android/build.gradle
Library/Core/UnoCore/Targets/Android/gradle/wrapper/gradle-wrapper.properties

This upgrades to Gradle 4.4, and Gradle-plugin 3.1.3.
This gives access to a new feature called "Instant Run", and we avoid being asked if we want to upgrade every time we open a generated project in Android Studio.

Android: upgrade Gradle versions

---

src/compiler/Uno.Compiler.Core/Syntax/UxlProcessor.cs

Warning messages should use a warning-code (instead of an error-code), and fix some formatting.

UxlProcessor cleanup

---

Library/Core/UnoCore/Targets/Android/Uno/Base/JNI.uno
Library/Core/UnoCore/Targets/Android/Uno/Graphics/GLHelper.cpp

This expression will always be true, so remove it to avoid compile-time warning on new build-tools.

Android: remove self-comparison in GLHelper.cpp

---

Library/Core/UnoCore/Targets/Android/Android.uxl
Library/Core/UnoCore/Targets/Android/app/build.gradle
Library/Core/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
tests/src/AndroidNativeDependency/AndroidNativeDependency.unoproj
tests/src/AndroidNativeDependency/App.uno

This feature will extract native libraries from downloaded AARs, so that we can
use them in our Uno/C++ code and make the NDK able to link them.
The extracted libraries are also added to search-paths in CMakeLists.txt, so we
can simply link them without worrying about actual paths.
I'm currently using this feature to build an app using the ARCore SDK, and it
would be cool if I could test the next version of Fuse Studio on my app...

Android: add Gradle.Dependency.NativeImplementation

---

Library/Core/UnoCore/Targets/Android/Dependencies.uxl
Library/Core/UnoCore/Targets/Android/app/build.gradle
Library/Core/UnoCore/Targets/Android/build.gradle
Library/Core/UnoCore/UnoCore.unoproj

When already "deep in Android-land" I got a compelling feeling to clean up our build system even more.
Testing: I've tried various apps from our examples-repo (cards-menu, inbox and weather-app), and they all still work.
After this PR I want to follow-up by upgrading the three android-support libraries to `27.1.1`, and that should make us good for a while I think, Android-wise (because support-libs should match the build-tools version).

Android build system cleanup

---

Library/Core/UnoCore/Targets/Android/Dependencies.uxl

Support libraries should match the major version of build-tools used.
So, now they do.

Android: upgrade support libraries to 27.1.1

---

Library/Core/UnoCore/Source/OpenGL/GL.uno
Library/Core/UnoCore/Source/Uno/Array.uno
Library/Core/UnoCore/Source/Uno/Buffer.uno
Library/Core/UnoCore/Source/Uno/Graphics/DeviceBuffer.uno
Library/Core/UnoCore/Source/Uno/Graphics/IndexBuffer.uno
Library/Core/UnoCore/Source/Uno/Graphics/Support/DotNetTexture.uno
Library/Core/UnoCore/Source/Uno/Graphics/TextureCube.uno
Library/Core/UnoCore/Source/Uno/Graphics/VertexBuffer.uno
Library/Core/UnoCore/Source/Uno/Runtime/Implementation/Internal/BufferConverters.uno
Library/Core/UnoCore/Source/Uno/Runtime/Implementation/ShaderBackends/OpenGL/GLHelpers.uno
Library/Core/UnoCore/Source/Uno/Runtime/InteropServices/GCHandle.uno
src/compiler/Uno.Compiler.Core/Syntax/Generators/ShaderGenerator.VertexAttrib.cs
src/runtime/Uno.Runtime.Core/OpenGL/GL.cs

Here comes some commits focused on improving our interfacing with OpenGL.
In particular, this will make it really easy to finally deprecate the `Uno.Buffer` class - since it's no longer needed by the compiler, nor the API.
We also avoid extra copy passes on index and vertex arrays from `draw`-statements, and just generally make things nicer.
After this, I plan to follow up by replacing and deprecating `Uno.Buffer`, and make patches for other known repositories ready for when a new Uno release is available.

OpenGL and Uno.Graphics clean-ups

---

Library/Core/UnoCore/Backends/CPlusPlus/CPlusPlus.uxl
Library/Core/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.cpp
Library/Core/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.h
src/compiler/Uno.Compiler.Backends.CPlusPlus/CppGenerator.cs

The old iOS bindings haven't been used in a long time, and this gets some more old code out of the way.

C++: remove support for legacy iOS bindings

---

Library/Core/UnoCore/Source/Uno/Diagnostics/AllocateEvent.uno
Library/Core/UnoCore/Source/Uno/Diagnostics/EnterEvent.uno
Library/Core/UnoCore/Source/Uno/Diagnostics/ExitEvent.uno
Library/Core/UnoCore/Source/Uno/Diagnostics/FreeEvent.uno

This removes some deprecation warnings received when building `UnoCore`.

UnoCore: deprecate profile events in Uno.Diagnostics

---

Library/Core/UnoCore/Tests/Buffer.Test.uno
Library/Core/UnoCore/Tests/Color.Test.uno
Library/Core/UnoCore/Tests/Math.Test.uno
Library/Core/UnoCore/Tests/Random.Test.uno

This removes warnings received when building `UnoCore.Test`.

Remove warnings in UnoCore.Test

---

Library/Core/UnoCore/Source/Uno/Array.uno
src/compiler/Uno.Compiler.API/Domain/IL/Types/RefArrayType.cs
src/compiler/Uno.Compiler.Core/Syntax/Builders/TypeBuilder.cs

This removes some needless code related to the `Length` property on arrays.

Array clean-up

---

Library/Core/UnoCore/Backends/CPlusPlus/Uno/Support.h
Library/Core/UnoCore/Source/Uno/Buffer.uno
Library/Core/UnoCore/Source/Uno/ByteArrayExtensions.uno
Library/Core/UnoCore/Source/Uno/Content/Fonts/CppFontFace.uno
Library/Core/UnoCore/Source/Uno/Content/Fonts/DotNetFontFace.uno
Library/Core/UnoCore/Source/Uno/Content/Fonts/RenderedGlyph.uno
Library/Core/UnoCore/Source/Uno/Content/Images/Bitmap.uno
Library/Core/UnoCore/Source/Uno/IO/BinaryReader.uno
Library/Core/UnoCore/Source/Uno/IO/BinaryWriter.uno
Library/Core/UnoCore/Source/Uno/Runtime/Implementation/BufferImpl.uno
Library/Core/UnoCore/Tests/Buffer.Test.uno
Library/Core/UnoCore/Tests/ByteArrayExtensions.Test.uno
Library/Core/UnoCore/Tests/UnoCore.Test.unoproj
Library/Core/UnoCore/UnoCore.unoproj
tests/src/UnoTest/ShaderGenerator/BatchIndexBuffer.uno
tests/src/UnoTest/ShaderGenerator/BatchVertexBuffer.uno

This introduces a new `Bytes` class containing extension methods for manipulating `byte` arrays directly.
We can now use plain `byte[]`, which are more practical than creating `Buffer` objects when we want to work with byte data, and the interface is still pretty much identical.
I think this is a good deal, and patches for `fuselibs` are also ready: https://github.com/mortend/fuselibs/tree/replace-buffer

Replace Buffer class

---

lib/Uno.Net.Http/Tests/Http.Test/UriTests.uno

This avoids compile-time deprecation warnings when running tests.

Http.Test: deprecate two tests in UriTests

---

lib/UnoCore/Targets/Native/CMakeLists.txt
lib/UnoCore/Targets/Native/Native.uxl

Add new `LinkLibrary.{Debug, Release}` elements for the Native build target, and disable warning in generated code.

Native target link elements and warning fix

---

lib/UnoCore/Backends/CPlusPlus/Uno/Memory.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/_config.h

This adds a new `U_ERROR()` macro to more conveniently report errors in C++ code.
The macro has also been useful in some external code I'm working on.

C++: add U_ERROR() macro

---

src/runtime/Uno.AppLoader-WinForms/UnoGLControl.cs

This makes noise in the terminal and isn't really helpful. I think it's better
to remove the warning code.

Uno.AppLoader-WinForms: don't warn about unrecognized input

---

src/common/Uno.Common/Logging/Log.cs

When working with UX documents I keep getting warnings originating from code
produced by the UX-to-Uno code generator, i.e.:
.uno\ux15\Icon.g.uno(21.18): W0000: Icon.Size hides inherited member Fuse.Elements.Element.Size -- use the 'new' modifier if hiding is intentional
Silencing warnings from generated code is a lot easier than fixing the code
generator itself, so let's do that for now.

Uno.Common: silence warnings from generated code

---

lib/UnoCore/Backends/CPlusPlus/Uno/Support.cpp

Reorder variables to delete our objects in correct order.
All Uno methods calling this are deprecated, and apparently this hasn't been
used in a long time. I ended up using it while trying some things, so let's
just fix it.

UnoCore: fix crash in uLoadXliTexture()

---

src/compiler/Uno.Compiler.Core/Syntax/Macros/MacroExpander.cs

Early-out on empty string in MacroExpander. This fixes error when parsing
@(Project.iOS.SystemCapabilities.Push:Test(1,0)) when building for iOS, and
the property is missing in the project file.
../../uno/lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist(1): E0000: Unable to parse bool ''

Uno.Compiler: fix iOS build error

---

src/compiler/Uno.Compiler.Frontend/Preprocessor/Preprocessor.cs

This improves the preprocessor and fixes an issue when building for iOS.
The issue is that we end up with a string similar to ` -->`, which is invalid XML and causes syntax error.
After the fix we instead end up with ``, which is fine.

Preprocessor improvements

---

CHANGELOG.md
lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/prebuilt/uno-base.stuff

The new NDK r18 removes `libgnustl` and `libstlport`.
These patches switches to `libc++` in uno and uno-base and makes us compatible with NDK r18.
Luckily, fuselibs still works out-of-the-box.

NDK r18 support

---

lib/UnoCore/Targets/Android/app/build.gradle

This was a hint for the build system to choose the first one in case multiple
versions of the library are found. Since we no longer use gnustl after it was
removed in NDK r18 (f99047247218c30cae5f8cb5c8d437b50a45c151), we no longer
need the hint (this was mentioned in #109).

Android: remove gnustl packaging option

---

lib/Uno.Net.Sockets/Dns.uno
lib/Uno.Net.Sockets/Socket.uno

Add casts to avoid C++ compile-time warnings.

Uno.Net.Sockets: fix C++ warnings

---

lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/DownloadTask.java
lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/PRNGFixes.java
lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/UploadTask.java
lib/UnoCore/Targets/Android/com/fuse/deprecated/MessageBoxHelper.java

LICENSE.txt contains our license information and I think the headers can be removed.

drop license header in Java files

---

src/engine/Uno.Build/BuildDriver.cs

Use the NativePath property for consistent path strings on Windows, fixing
strings like `foo\bar/baz.stuff`.

Uno.Build: fix path inconsistencies

---

lib/UnoCore/Targets/Native/CMakeLists.txt

This will not open a console window when launching an app using explorer,
but we'll still get console output when launching apps from the
command-line.

Native: don't show console window on Windows

---

lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml

Currently, setting orientation to Landscape will lock the app in only one
landscape mode and the app will not rotate according to the sensor. This is
not the expected behaviour.
This fixes so that setting orientation to Landscape will rotate the app
according to the sensor. It is also possible to specify LandscapeLeft or
LandscapeRight to force only one of the landscape modes.

Android: support both Landscape modes

---

lib/Uno.Net.Sockets/IPAddress.uno

This fixes the following linker error on WIN32 if IPAddress is used without
Socket:
Uno.Net.g.obj : error LNK2019: unresolved external symbol inet_ntop referenced in function "public: static struct uString * __cdecl g::Uno::Net::IPAddress::IPv6AddressToString(struct uArray *)" (?IPv6AddressToString@IPAddress@Net@Uno@g@@SAPEAUuString@@PEAUuArray@@@Z)

Uno.Net.Sockets: fix linker error

---

.travis.yml

The C# test runner have (randomly) failed a lot on Travis lately, even if all
tests have actually passed, with the following error message:
NUnit.Engine.NUnitEngineUnloadException : Multiple exceptions encountered. Retrieve AggregatedExceptions property for more information
----> System.Runtime.Remoting.RemotingException : Tcp transport error.
----> System.Runtime.Remoting.RemotingException : Connection closed
The command "mono NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe --agents=1 \
src/testing/Uno.TestRunner.Tests/bin/Debug/Uno.TestRunner.Tests.dll \
src/ux/Uno.UX.Markup.AST/Tests/bin/Debug/Uno.UX.Markup.AST.Tests.dll \
src/ux/Uno.UX.Markup.UXIL/Tests/bin/Debug/Uno.UX.Markup.UXIL.Tests.dll
" exited with 251.
The C# tests are run on AppVeyor in any case. I think that is safe …

Disable C# tests on Travis

---

lib/UnoCore/Targets/Android/Dependencies.uxl

Myself and others have occasionally experienced trouble when downloading
dependencies when building for Android, and this seems to fix the problem.
I haven't seen this problem in a while and it seems to have been caused by
temporary issues on Google servers, but it doesn't cause any harm to add the
fix anyway, hopefully avoiding similar trouble in the future.

Android: add google repository to all projects #130

---

lib/Uno.Net.Sockets/Dns.uno
lib/UnoCore/Backends/CPlusPlus/Uno/Memory.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.h
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/uObjC.String.mm
lib/UnoCore/Source/Uno/String.uno
lib/UnoCore/Source/Uno/Text/Utf8.uno
lib/UnoCore/Source/Uno/Type.uno

size_t is commonly used to represent indices and lengths in C/C++ code, and
instead of adding casts to int32_t, we change the interface of uArray and
uString to accept size_t. This seems to align better with a lot of C/C++
code, and is non-breaking since int32_t implicitly converts to size_t and
vice versa. Since many call sites were size_t to begin with we can remove
some explicit casts to int32_t, and since we can remove some often called
"< 0" checks the code is in theory a bit faster now than it was before.
This fixes a few instances of the following warning:
warning C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data

C++: switch to size_t in uArray and uString

---

src/compiler/Uno.Compiler.Core/Syntax/Compilers/FunctionCompiler.NameResolver.Identifier.cs
tests/src/UnoTest/ShaderGenerator/NestedBlock.uno
tests/src/UnoTest/UnoTest.unoproj

This fixes bugs when accessing members of a parent class from inside a nested
block.

Uno.Compiler: fix name resolver bug

---

lib/Uno.Net.Http/HttpMessageHandler.uno
lib/Uno.Net.Http/HttpMessageHandlerRequest.uno
lib/Uno.Net.Http/Implementation/Xli/XliHttpRequest.cpp.uxl
lib/Uno.Net.Http/Implementation/Xli/XliHttpRequest.uno
lib/Uno.Net.Sockets/Dns.uno
lib/Uno.Net.Sockets/IPAddress.uno
lib/Uno.Net.Sockets/NetworkHelpers.uno
lib/Uno.Net.Sockets/Socket.uno
lib/UnoCore/Targets/Native/Native.uxl

We're using MSVC version 15 and not 12, so this define is outdated and should
be removed in the future.

UnoCore: deprecate MSVC12 define

---

lib/UnoCore/Tests/Collections/HashSet.Test.uno
src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.Type.cs

This will catch more compile-time errors like the following:
E4128: X is less accessible than Y

Uno.Compiler: verify visibility of generic arguments

---

src/compiler/Uno.Compiler.Core/Syntax/UxlProcessor.cs

I experienced a problem with an image in an incompatible pixel format, and
this makes it easier to see which image file is causing the problem.

Uno.Compiler: report image filename when WriteImageFile() fails

---

Documentation/CommandLineReference.md
README.md
scripts/build.sh
src/engine/Uno.Build/Packages/LibraryBuilder.cs
src/engine/Uno.Build/Packages/LibraryProject.cs
src/engine/Uno.Build/Packages/UpkBuilder.cs
src/main/Uno.CLI/Packages/Doctor.cs

This comes with some improvements to the `uno doctor` command, most notably the ability to control which projects are actually built by passing directories on the command-line.
This makes it possible to build the right version when there are multiple copies of for example `fuselibs` in flight.

uno doctor improvements

---

src/compiler/Uno.Compiler.Backends.CPlusPlus/CppWriter.cs

The source line numbers aren't really useful, and I think the output is
cleaner without.

C++: don't output source line numbers

---

.appveyor.yml
.gitignore
.travis.yml
scripts/test.sh

This fixes up test.sh and brings back UnoTest, UXTest and our old compiler
tests, which are currently not being run.
Both AppVeyor and Travis now run tests by invoking test.sh, which reduces
duplication and seems to be cleaner than it was before.

Run more tests on CI

---

src/compiler/Uno.Compiler.Backends.CIL/CilGenerator.Compile.cs
src/compiler/Uno.Compiler.Backends.CIL/CilType.cs

The signature becomes broken when calling PopulateParameter() from CilType,
and moving this code back to CilGenerator fixes the regression after #131.

CIL: fix crash when calling PInvoke method

---

.appveyor.yml
lib/UnoCore/Backends/CIL/CIL.uxl
lib/UnoCore/Targets/iOS/run.sh
lib/UnoCore/prebuilt/Uno.Native.stuff
lib/UnoCore/prebuilt/uno-base.stuff

It looks like all dependencies hosted on files.fusetools.com are no longer available, effectively breaking all versions of Fuse and Fuse Studio ever released. Hopefully they will come back again soon...
Dependencies are now repackaged and hosted on nuget.org to get things up and running again and to avoid problems with files.fusetools.com in the future.

Fix dependency downloads

---

src/compiler/Uno.Compiler.Backends.UnoDoc/UnoDocBackend.cs

Without this, we'll fail generating the reference documentation, because
we have some API that only have C++ API (the corresponding .NET API is
provided by different, API-compatible means).

UnoDoc: always support linking

---

lib/UnoCore/Backends/CSharp/Uno/ApplicationContext.cs
src/compiler/Uno.Compiler.Backends.PInvoke/Uno.Compiler.Backends.PInvoke.csproj
src/compiler/Uno.Compiler.Backends.UnoDoc/Uno.Compiler.Backends.UnoDoc.csproj
src/compiler/Uno.Compiler.Extensions/Uno.Compiler.Extensions.csproj
src/engine/Uno.Build.Targets/Uno.Build.Targets.csproj
src/engine/Uno.Build/Uno.Build.csproj
src/engine/Uno.ProjectFormat/Uno.ProjectFormat.csproj
src/main/Uno.CLI.Main/Uno.CLI.Main.csproj
src/runtime/Uno.Runtime.Core/Uno/ApplicationContext.cs
src/testing/Uno.CompilerTestRunner/Uno.CompilerTestRunner.csproj
src/testing/Uno.TestRunner.BasicTypes/Uno.TestRunner.BasicTypes.csproj
src/testing/Uno.TestRunner.Tests/Uno.TestRunner.Tests.csproj
src/testing/Uno.TestRunner/Uno.TestRunner.csproj
src/ux/Uno.UX.Markup.AST/Tests/Helpers/TestHelpers.cs
src/ux/Uno.UX.Markup.AST/Tests/Uno.UX.Markup.AST.Tests.csproj
src/ux/Uno.UX.Markup.CodeGeneration/Uno.UX.Markup.CodeGeneration.csproj
src/ux/Uno.UX.Markup.CompilerReflection/Uno.UX.Markup.CompilerReflection.csproj
src/ux/Uno.UX.Markup.UXIL/Tests/Uno.UX.Markup.UXIL.Tests.csproj

This clean-up removes unnecessary references in C# projects.

remove unused C# references

---

src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/CommentParser.cs
src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/SourceComment.cs
src/compiler/Uno.Compiler.Backends.UnoDoc/Builders/Syntax/SyntaxGenerator.cs

This PR fixes some problems where JSON strings get "\r\n" when serialized on Windows.

Uno doc CRLF

---

lib/UnoCore/Source/Uno/Text/Ascii.uno
lib/UnoCore/Tests/Text/AsciiEncoding.Test.uno

Passing empty string/array should return empty array/string.

UnoCore: don't return null in Uno.Text.Ascii

---

lib/UnoCore/Targets/Android/@(Java.PackageDirectory)/@(Activity.Name).java
lib/UnoCore/Targets/Android/Android.uxl
src/compiler/Uno.Compiler.Core/Syntax/UxlProcessor.cs

I ran into a situation where I needed to override a method from Activity on Android.
Providing my own base class allows me to do that in a pretty clean way.

Android: add @(Activity.BaseClass) property

---

lib/UnoCore/Source/Uno/String.uno
src/compiler/Uno.Compiler.Frontend/Analysis/Parser.cs

Multiple ARGS are expanded to a call to string.Join(" ", ...ARGS).
debug_log 1, 2, 3;
... becomes
1 2 3
... which is useful in cases where you don't want to type
debug_log 1 + " " + 2 + " " + 3;

Uno.Compiler: support debug_log with multiple arguments

---

lib/UnoCore/Targets/Android/app/build.gradle

We want this value to to match 'build' in https://github.com/fuse-open/uno/blob/master/lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt#L19,
but ${buildDir} don't expand to 'build' and instead gives '${buildDir}'...
Maybe something changed with quoting in newer gradle versions or maybe the
variable don't exist anymore, but hardcoding the value fixes the problem.

Android: hardcode ${buildDir}

---

src/engine/Uno.ProjectFormat/PropertyDefinitions.cs

These project properties are no longer used since removing the JavaScript
backend and WebGL targets.

Uno.ProjectFormat: drop legacy HTML properties

---

lib/UnoCore/Source/Uno/Guid.uno
lib/UnoCore/prebuilt/uno-base.stuff

Following up with some more fixes for Linux.
I'm now able to successfully run the full test suite locally, except UXTest which is also crashing on Win32 currently I think, and is ignored on CI.
I tried to add Linux on Travis, but currently we immediately get segfaults when running tests (maybe related to GL?). I guess the next step is to try valgrind and see if we can get a useful stack trace. I will probably look into this more later when I get the chance. My current changes to the travis script are here: https://github.com/mortend/uno/commit/6158a4c106009e9e573a0241e0cbd53d7b01bbab

More Linux support

---

.travis.yml
lib/UnoCore/Source/Uno/IO/Directory.uno
scripts/test.sh
src/testing/Uno.CompilerTestRunner/Program.cs
src/testing/Uno.TestRunner.BasicTypes/CommandLineOptions.cs
src/testing/Uno.TestRunner/TestProjectRunner.cs

This makes sure things build on Linux.
Because we get Segmentation Fault on Travis when we run tests, we only build them. Locally, tests run fine though.

Build for Linux on Travis

---

lib/UnoCore/Source/Uno/Rect.uno
lib/UnoCore/Source/Uno/Runtime/Implementation/ShaderBackends/OpenGL/GLDrawCall.uno
lib/UnoCore/Source/Uno/Runtime/Implementation/ShaderBackends/OpenGL/GLProgram.uno
lib/UnoCore/Source/Uno/String.uno
lib/UnoCore/Source/Uno/Text/Ascii.uno
lib/UnoCore/Source/Uno/Text/StringBuilder.uno
lib/UnoCore/Source/Uno/Text/Utf8.uno
lib/UnoCore/Tests/String.Test.uno
lib/UnoCore/Tests/Text/AsciiEncoding.Test.uno
lib/UnoCore/Tests/Text/Utf8Encoding.Test.uno

Avoid a bunch of string allocations/copies on C++, verify some arguments, and add `GetString(byte[], int, int)` overloads for `Ascii` and `Utf8` to decode a subset of the array.

Various UnoCore improvements

---

lib/UnoCore/Backends/CPlusPlus/Uno/_main.cpp
src/runtime/Uno.AppLoader-MonoMac/UnoGLView.cs
src/runtime/Uno.AppLoader-WinForms/MainForm.cs
src/testing/Uno.TestRunner/TestProjectRunner.cs

Since nothing is shown in the window when running tests it's better to hide
the window in this scenario.

Don't show window when running tests

---

lib/UnoCore/Backends/CPlusPlus/Uno/_main.cpp
lib/UnoCore/Source/Uno/IO/Directory.uno

This fixes a regression after #179. Also fixes a C++ warning again after discovering that casting to void didn't silence the warning.

Fix regression after #179

---

lib/UnoCore/Backends/CPlusPlus/Uno/NativeStackTrace.cpp
lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/app/build.gradle
lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
lib/UnoCore/prebuilt/uno-base-pinvoke.uxl
lib/UnoCore/prebuilt/uno-base.stuff
lib/UnoCore/prebuilt/uno-base.uxl
src/engine/Uno.ProjectFormat/PropertyDefinitions.cs

This enables building any combination of the following architectures.
* `armeabi-v7a`
* `arm64-v8a`
* `x86`
* `x86_64`
Architectures can be specified in the project file, for Debug and Release separately.
"Android": {
"Architectures": {
"Debug": ["arm64-v8a"],
"Release": ["armeabi-v7a", "arm64-v8a"]
}
}
By default we'll build `arm64-v8a` for debug, and `armeabi-v7a` + `arm64-v8a` for release. Building multiple architectures increases build time significantly, so while testing/developing we usually only want to build one.
Related: #154, https://github.com/fuse-open/fuselibs/pull/1274

Android: support fat/multi-arch builds

---

lib/UnoCore/Source/Uno/Graphics/DeviceBuffer.uno
lib/UnoCore/Source/Uno/Text/Ascii.uno
lib/UnoCore/Source/Uno/Text/Utf8.uno

This adds a method to upload a sub-array to `DeviceBuffer`.
While at it I added input validation which also led me to fix bugs I discovered in code recently added to `Uno.Text.{Ascii,Utf8}`.

UnoCore: sub-array support in DeviceBuffer

---

lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
src/compiler/Uno.Compiler.Backends.CPlusPlus/CppBackend.cs

This will use a response file to pass arguments to linker, instead of the command-line, and enables us to use normal-length filenames on Android again. Because we now completely avoid the "command too long" issue on Windows.

Android: use response file

---

.appveyor.yml
.travis.yml

This will enable U_ASSERT(), U_ASSERT_PTR() and some other run-time checks while running tests, and should make us feel a little bit safer.

Enable DEBUG_UNSAFE when testing C++

---

src/compiler/Uno.Compiler.Frontend/Analysis/Parser.cs

I see some people prefer to use debug_log with parens, so let's allow using
parens when there are multiple arguments too.

Parser: optional parens around debug_log args

---

lib/UnoCore/Targets/Native/build.sh
lib/UnoCore/Targets/Native/run.sh

Now we don't need to delete the CMake cache due to switching generators,
which speeds up subsequent builds.
Also, don't try to launch Xcode if passing --debug on Linux.

Native: always use Xcode on macOS

---

src/engine/Uno.Build/Packages/PackageCache.cs

GetFileNameWithoutExtension() strips directory components which gives us a
problem when transpiling files contained in a sub-directory.
Using ChangeExtension() instead fixes the problem.

FuseJS: fix transpiled path

---

src/engine/Uno.Build/Packages/LibraryBuilder.cs

This enables building NPM packages from a single Uno project, and the project
file is located in the root directory of the repository. Uno doctor will pick
it up when Packages.SourcePaths is set to `.`.
Useful when converting existing Uno projects to NPM packages.

LibraryBuilder: find projects directly in Packages.SourcePaths

---

lib/UnoCore/Targets/Native/CMakeLists.txt

This requires CMake v3.6 (current CMake is v3.15).

Native: set startup project for Visual Studio

---

lib/FuseJS.Transpiler/src/package-lock.json

In #203 we ran `npm audit fix` to replace vulnerable packages, but GitHub still displays the security alert.
This PR is a second attempt to silence the alert by explicitly upgrading `lodash`.

FuseJS.Transpiler: upgrade lodash

---

src/engine/Uno.ProjectFormat/IncludeGlobber.cs

Projects will now transpile TypeScript files by default without having to
edit "*.ts:FuseJS" into the project file first, and this is convenient for
most/all users.
Note that we don't automatically add JavaScript files because transpiling
only applies to scripts that use the new Models API, so we don't know if
a JavaScript file should be transpiled or not. This is not a problem for
TypeScript files, who very likely always need to be transpiled.

Uno.ProjectFormat: automatically add .TS files as FuseJS

---

lib/UnoCore/Backends/CPlusPlus/Uno/WinAPIHelper.h

To solve the following build errors (when using preview).
Uno.IO.g.cpp(698): error C2039: 'CreateFileW': is not a member of 'g::Uno::IO::Bundle'
Uno.IO.g.cpp(791): error C2039: 'CreateFileW': is not a member of 'g::Uno::IO::Bundle'

UnoCore: undef CreateFile in WinAPIHelper.h

---

src/common/Uno.Common/Compiler/SourcePackage.cs
src/common/Uno.Common/IO/Disk.cs
src/common/Uno.Common/Logging/LogState.cs
src/compiler/Uno.Compiler.Backends.CIL/CilBackend.cs
src/compiler/Uno.Compiler.Core/BuildEnvironment.cs
src/engine/Uno.Build/Stuff/DownloadCache.cs
src/engine/Uno.ProjectFormat/IncludeGlobber.cs
src/engine/Uno.ProjectFormat/ProjectGlobber.cs
src/main/Uno.CLI/Program.cs
src/testing/Uno.TestRunner.Loggers/ConsoleLogger.cs

Some subtle tweaks, mostly to some logging code.

Logging tweaks

---

src/ux/Uno.UX.Markup.AST/Generator.cs
src/ux/Uno.UX.Markup.AST/Parser.cs
src/ux/Uno.UX.Markup.Common/Attributes.cs
src/ux/Uno.UX.Markup.UXIL/ClassNode.IDataType.cs
src/ux/Uno.UX.Markup.UXIL/ClassNode.cs
src/ux/Uno.UX.Markup.UXIL/Compiler.cs

UX classes with Uno code-behinds don't work properly in the simulator. To
solve this, we can set this attribute to false to disable bytecode generating
and always instantiate the precompiled Uno class instead.

Uno.UX.Markup: add ux:Simulate attribute

---

src/main/Uno.CLI/Android/AdbRunner.cs

Some users need to run apps on network devices, but v1.12 introduced a change
that ignores network devices.
This patch makes ignoring network devices opt-in, and users that hasn't set
Android.IgnoreNetworkDevices will get the old behaviour restored, as things
used to be in pre-v1.12.
Users that want to ignore network devices can add this to their ~/.unoconfig:
Android.IgnoreNetworkDevices: true

AdbRunner: introduce Android.IgnoreNetworkDevices config #206

---

scripts/pack.sh

Don't terminate the script if a git command fails.
This fixes building .tar.gz files downloaded from GitHub, reported broken in
https://forums.fusetools.com/t/unable-to-compile-uno-fatal-not-a-git-repository/7817/1

pack.sh: support building outside of Git

---

src/common/Uno.Common/Diagnostics/PlatformDetection.cs
src/engine/Uno.Configuration/Format/StuffFile.cs

Before, `~` expanded to `%HOME%` on all platforms which is not robost.
Now, we get `~` in a more robost way that provides several fallbacks and throws an exception if the directory could not be found.
This patch fixes so that more users will get their `~/.unoconfig` loaded properly.

Uno.Configuration: expand ~ to HomeDirectory

---

lib/UnoCore/Targets/Android/app/src/main/res/values/styles.xml

Solve crash apps with windowIsTranslucent together with screenOrienta…tion="portrait" on Android 8 Oreo.
https://www.reddit.com/r/androiddev/comments/ap5zdm/dont_use_windowistranslucent_together_with/
https://forums.fusetools.com/t/problem-with-android-api-27-and-later/7430
https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o/50832408#50832408

Solve crash apps with windowIsTranslucent

---

lib/UnoCore/Targets/Android/app/src/main/res/values/styles.xml

#211 came in with an extra '@' character, causing compile-time error.
error: failed linking references.
C:\Users\morten\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.1.1.aar\c7791c5f011e3ee28990f27611eb82c8\res\values\values.xml: AAPT: error: expected boolean but got (raw string) @'false'.

Android: fix compile error

---

lib/UnoCore/Targets/Android/build.bat
lib/UnoCore/Targets/Android/build.sh

Sometimes Uno needs a --force to clear its cache and find the newly installed
android-build-tools.

Android: inform user about --force

---

lib/UnoCore/Targets/Android/build.bat

After upgrading CMake to 3.10.2.4988404 in SDK Manager, I started getting
this error when building.
{"cookie":"","inReplyTo":"configure","message":"CMake Error: CMake was unable to find a build program corresponding to \"Ninja\".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.","title":"Error","type":"message"}
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.
You probably need to select a different build tool.
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.
You probably need to select a different build tool.
Configuration failed.
Adding ninja.exe to PATH solves the problem.

Android: add ninja.exe to PATH on Windows

---

CHANGELOG.md
src/engine/Uno.ProjectFormat/PropertyDefinitions.cs

Some users have reported issues when running Android apps after upgrading to
Uno v1.12, very likely because their devices don't support arm64-v8a, which
is the new default ABI for debug builds.
This seems like a regression, and we should probably have kept armeabi-v7a as
the default ABI in #186 for better compatibility.

Android: revert default ABI #214

---

CHANGELOG.md
lib/UnoCore/Targets/iOS/@(LaunchImages)/Contents.json
lib/UnoCore/Targets/iOS/iOS.uxl

Support for iPhone XR and iPhone XS Max Launch Image has been added.
Updated Changelog file to accommodate changes from this PR and https://github.com/fuse-open/uno/pull/220

Add iPhone Xr and Xs Max Launch Images and update CHANGELOG

---

README.md

What it does:
* adds a badge to show the latest number of financial contributors
* adds a banner displaying contributors to the project on GitHub
* adds a banner displaying all individuals contributing financially on Open Collective
* adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website
(Adapted from https://github.com/fuse-open/fuse-studio/pull/44)

README: add Open Collective info

---

README.md
bin/uno.js
package-lock.json
package.json

The [dotnet-run](https://www.npmjs.com/package/dotnet-run) package will detect Mono/.NET or automatically download a suitable version for your system.
> When we can find Mono v5.4.1.7 or greater on your system, we'll use your existing installation. By default we'll download v6.0.0.311 automatically.
>
> We provide minimal Mono releases for macOS, much smaller than official releases. Our v6.0.0.311 is distributed as a 33.6 MB tarball, which installs faster and is more than ten times smaller than the official pkg installer at 362.2 MB. Our package is unobtrusive to your system and will safely co-exist with any existing Mono installation you may or may not have from before.

macOS: install Mono automatically

---

src/compiler/Uno.Compiler.API/Domain/IL/Types/DataType.cs

This change will cause the C++-generator to drop unnecessary calls to
Char_typeof()->Init() and String_typeof()->Init() in all static members
of char and string classes.
This will speed things up because of less overhead at run-time, and static
members of these two classes are typically invoked very frequently.

C++: optimize string and char classes

---

lib/UnoCore/Targets/iOS/run.sh

Our version of `ios-deploy` that is included in `uno-base` is outdated and no longer works with the most recent version of iOS (#210).
To get around this problem we'll use the system-installed version instead.
Currently, the most recent beta version of `ios-deploy` is required for iOS 13, which can be installed by running this command.
```
npm install ios-deploy@beta -g
```

iOS: switch to user-installed ios-deploy

---

src/engine/Uno.Build/Packages/LibraryBuilder.cs
src/engine/Uno.Build/Packages/PackageCache.cs
src/main/Uno.CLI/Packages/Doctor.cs

Project filenames can now be passed directly to 'uno doctor' or via
Packages.SourcePaths in .unoconfig.
This syntax makes a lot of sense when you want to be explicit about
which projects to build.

uno doctor: support passing filenames to project files

---

docs/configuration.md
lib/UnoCore/Targets/Native/Native.uxl
lib/UnoCore/Targets/Native/build.bat
lib/UnoCore/Targets/Native/build.sh
lib/UnoCore/Targets/Native/run.bat
lib/UnoCore/Targets/Native/run.sh
src/engine/Uno.Build/JavaScript/FuseJS.cs

* Provide instructions on how to install CMake when not found.
* Drop `Tools.CMake` and `Tools.Node` config properties.
* Always run `cmake` and `node` from PATH.
Related to #227

Detect CMake on Windows

---

src/main/Uno.CLI/Diagnostics/Config.cs

This is sometimes useful to know, so when invoking 'uno config' we'll print
something like the following.
Config defines
DEV WIN32 WINDOWS X64

uno config: print list of current defines

---

src/main/Uno.CLI/Projects/BuildCommand.cs

This switch will override any --run or --debug arguments, and make sure we
don't run anything after build completion.
This is sometimes useful in combination with NPM scripts that already specify
--run or --debug, to disable those:
npm run android -- --build-only

uno build: add --build-only switch

---

lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/app/src/main/res/drawable/splash_background.xml
lib/UnoCore/Targets/Android/app/src/main/res/values/colors.xml
lib/UnoCore/Targets/Android/app/src/main/res/values/styles.xml
lib/UnoCore/Targets/Android/com/fuse/App.java

- fixed flash of a screen when no splash
- added .unoproj option to add splash screen:
```
"Android": {
"Splash": {
"Enabled": true,
"SplashBackgroundColor": "#9846EF",
"SplashLogo": "Assets/splash_logo.png",		
},
}
```

Android Splash

---

lib/UnoCore/Targets/Android/app/src/main/res/values/styles.xml

The issue has been reported on the forum post : https://forums.fusetools.com/t/statusbar-is-missing-in-android-9/7912

fix a regression where android status bar is always hidden

---

lib/UnoCore/Targets/Android/app/build.gradle
lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml

```
"Android": {
"SupportedLanguages": ["en"],
"Bundle": {
"CompressNativeLibraries": true,
"Language": {
"EnableSplit": false
},
"Density": {
"EnableSplit": true
},
"ABI": {
"EnableSplit": true
}
},
...
```
Native Library Compression
- turn on/off compression: https://developer.android.com/studio/projects/dynamic-delivery/configure-base#base_manifest
App Supported Languages
- define apps official languages so that other language resources in plugins will be removed except for the apps official languages: https://developer.android.com/studio/build/shrink-code#unused-alt-resources
Bundle Base Split Options
- language, density and abi options are made available to turn on/off: https://developer.android.com/studio/projects/dynamic-delivery/configure-base#disable_config_apks
Supports Screens …

Android - Added Dynamic Delivery options

---

scripts/pack.sh

This drops $BRANCH and $SUFFIX, and simplifies logic (#208).
When updating an NPM package, the version field must be updated in
package.json, and all changes to package.json should be committed in Git.
This means that publishing an NPM package, pre-release or not, will always
involve updating package.json, committing, and pushing a tag in Git.
This also means that pack.sh should not manipulate version info read from
package.json, as it used to do in pre-NPM times for legacy reasons.

Simplify version info

---

.appveyor.yml
docs/build-instructions.md
package-lock.json
package.json

`xbash` is an NPM package that will detect Git for Windows and run `bash.exe` from there, or make a suggestion to install Git for Windows. So, now `bash.exe` no longer needs to added to PATH explicitly, and this makes commands such as `npm pack` more likely to just work.

Run Bash from Git for Windows

---

package.json
scripts/pack.sh
scripts/version.sh
src/GlobalAssemblyInfo.cs

This adds a script that's automatically run when using `npm version`. This makes sure version information in the NPM package and .NET assemblies are in sync.

Auto-sync version info

---

lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/build.bat
lib/UnoCore/Targets/Android/build.sh
lib/UnoCore/Targets/Android/run.bat
lib/UnoCore/Targets/Android/run.sh
src/engine/Uno.Build.Targets/Android/AndroidBuild.cs

This makes build-scripts aware of AAR (Android library) that are produced instead of APK when passing `-DLIBRARY`, and other fixes related to this.

Improve Android AAR support

---

lib/UnoCore/UnoCore.unoproj

This adds a file reference that was missing in the project, thus missing from `npm pack`-ed builds, causing Android builds to fail since #254.

UnoCore: add missing file to project

---

Makefile
docs/build-instructions.md

This will build Uno libraries in `lib/` only. Saves a lot of time when it's
not necessary to rebuild the compiler and everything.

Makefile: add lib target

---

lib/UnoCore/Targets/Android/@(Java.PackageDirectory)/@(Activity.Name).java
src/compiler/Uno.Compiler.Extensions/Foreign/Java/Entrypoints.cs
src/compiler/Uno.Compiler.Extensions/Foreign/Java/JavaClass.cs

This deletes some old internal methods that are no longer used, and marks generated `debug_log()` methods as obsolete. Users can easily use methods in `android.util.Log` directly instead.

Obsolete java code

---

lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/Android_com_fuse_ExperimentalHttp_HttpRequest.java
lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/HttpRequest.cpp.uxl
lib/Uno.Permissions/Permissions.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/BoolArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/ByteArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/CharArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/DoubleArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/FloatArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/IntArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/LongArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/ObjectArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/ShortArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/StringArray.java
lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/Android/UnoObject.java
lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/Uno/Base/JNI.uno
lib/UnoCore/Targets/Android/Uno/Base/Types.cpp.uxl
lib/UnoCore/Targets/Android/Uno/Base/UnoHelper.java
lib/UnoCore/Targets/Android/Uno/Base/Wrappers.cpp.uxl
lib/UnoCore/Targets/Android/Uno/EntryPoints.cpp
lib/UnoCore/Targets/Android/com/foreign/UnoWrapped.java
lib/UnoCore/UnoCore.unoproj
src/compiler/Uno.Compiler.Extensions/Foreign/Java/Delegates.cs
src/compiler/Uno.Compiler.Extensions/Foreign/Java/Entrypoints.cs
src/compiler/Uno.Compiler.Extensions/Foreign/Java/JavaClass.cs

The stuff in `com.Bindings` is mostly used by other code in `com.foreign`, so
merging the two seems cleaner and more consistent.
The old `com.Bindings` package is not used directly by any code in Fuselibs
or Fuse Compound, and very unlikely used directly outside of this repo.

Android: merge Java namespaces

---

src/engine/Uno.Build.Targets/BuildTargets.cs
src/engine/Uno.Build/BuildDriver.cs
src/engine/Uno.Build/ProjectCleaner.cs
src/main/Uno.CLI/Projects/Clean.cs

This adds more options to `uno clean` that make it possible to clean a specific target/configuration only.

clean: handle [target] and --configuration args

---

lib/UnoCore/prebuilt/uno-base.stuff

This upgrades the `uno-base-iOS-static` package, now including `arm64e` build.
Related: #253

iOS: add arm64e dependencies

---

lib/UnoCore/Targets/iOS/@(Project.Name).xcodeproj/project.pbxproj
lib/UnoCore/Targets/iOS/@(Schemes)/@(Project.Name).xcscheme
lib/UnoCore/Targets/iOS/Uno-iOS/AppDelegate.mm

This upgrades the Xcode project, avoiding warnings when opening in Xcode.
This also fixes/silences other compile-time warnings when building the generated project.
```
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/Fuse.Internal.g.mm:931:31: warning: 'UIFontDescriptorSystemDesignSerif' is only available on iOS 13.0 or newer [-Wunguarded-availability-new]
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/Fuse.Internal.g.mm:933:38: warning: 'fontDescriptorWithDesign:' is only available on iOS 13.0 or newer [-Wunguarded-availability-new]
/Users/morten/fuselibs/Tests/ManualTests/ManualTestingApp/build/iOS/Debug/src/iOS/ContainerView.mm:11:31: warning: 'userInterfaceStyle' is only available on iOS 12.0 or newer …
```

iOS: upgrade project & fix warnings

---

src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.Member.cs

This fixes a false error generated by the compiler when extern and abstract
are used together. For example:
extern(CPLUSPLUS) abstract void Foo();

Uno.Compiler: fix false error

---

lib/UnoCore/Source/Uno/Platform/GraphicsContextBackend.uno
lib/UnoCore/Source/Uno/Platform/Xli/XliGraphicsContext.uno

uGraphicsContext isn't available on mobile, and trying to access it gives
compile-time error when building with --no-strip.

UnoCore: fix extern conditions for XliGraphicsContext

---

lib/UnoCore/Targets/DotNet/DotNetDll.uxl
lib/UnoCore/Targets/DotNet/Executable.uxl
src/compiler/Uno.Compiler.Backends.CIL/CilBackend.cs
src/compiler/Uno.Compiler.Core/IL/Building/Entrypoint/MainClassFinder.cs

Two improvements when building with `-DLIBRARY`.
* Auto-generate main-class when building a library, avoiding compile-time error about main-class not found.
* Drop AppLoader when building a .NET library, we're only interested in the `.dll` file.

Library improvements

---

lib/UnoCore/Source/Uno/IO/Bundle.uno
lib/UnoCore/Source/Uno/Type.uno
src/compiler/Uno.Compiler.API/Domain/Extensions/BundleFile.cs
src/compiler/Uno.Compiler.API/IBundle.cs
src/compiler/Uno.Compiler.Backends.CIL/CilBackend.cs
src/compiler/Uno.Compiler.Backends.CIL/CilGenerator.Generate.cs
src/compiler/Uno.Compiler.Backends.CIL/CilGenerator.cs
src/compiler/Uno.Compiler.Backends.CIL/Extensions.cs
src/compiler/Uno.Compiler.Backends.Metadata/MetadataGenerator.cs
src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.cs
src/compiler/Uno.Compiler.Core/Syntax/Binding/NameResolver.MetaProperty.cs
src/compiler/Uno.Compiler.Core/Syntax/Builders/BundleBuilder.cs
src/compiler/Uno.Compiler.Core/Syntax/Compilers/FunctionCompiler.Expressions.Import.cs
src/compiler/Uno.Compiler.Core/Syntax/Generators/DrawCallGenerator.cs

This changes the compiler and CIL backend to emit one .NET assembly per Uno library, rather than one monolithic assembly containing all Uno libraries, which we did before for historical reasons.
This makes it easier to use assemblies built by Uno in other .NET projects, optimize build times by not rebuilding code that is already built, and to cache/prebuild assemblies to further optimize build times. We're also eliminating the need for generated C# projects (`Uno.Runtime.Core`), the C# backend and `corelib` target, because it's now trivial to build `UnoCore.dll` directly using Uno.

Modular .NET builds

---

src/testing/Uno.TestRunner.BasicTypes/CommandLineOptions.cs
src/testing/Uno.TestRunner.BasicTypes/Test.cs
src/testing/Uno.TestRunner.Loggers/ConsoleLogger.cs
src/testing/Uno.TestRunner.Tests/TestRunTests.cs
src/testing/Uno.TestRunner/TestProjectRunner.cs
src/testing/Uno.TestRunner/TestRun.cs

After dropping HTTP support in #283, we've seen tests timing out when it takes a long time to run the test suite (https://travis-ci.org/fuse-open/fuselibs/builds/643739010#L1714).
This PR fixes the problem by also dropping the timeout functionality, so now running tests will never time out inside the test runner. On AppVeyor and Travis, builds will automatically time out after one hour in any case.

TestRunner: Timeout fix after dropping HTTP

---

lib/UnoCore/Targets/Android/app/src/main/res/values/colors.xml
lib/UnoCore/Targets/Android/app/src/main/res/values/styles.xml

- Added default background color for default splash
- Fixed the translucent window setting to default to false, this fixes strange behaviour with or without orientation: https://www.reddit.com/r/androiddev/comments/ap5zdm/dont_use_windowistranslucent_together_with
https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o
Should only use when necessary: https://tech.pic-collage.com/something-about-android-windowistranslucent-641cc02ff66f

Android - default settings update

---

lib/UnoCore/Targets/iOS/@(Project.Name).xcodeproj/project.pbxproj
lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist
lib/UnoCore/Targets/iOS/@(Project.Name)/LaunchScreen.storyboard
lib/UnoCore/Targets/iOS/iOS.uxl
lib/UnoCore/UnoCore.unoproj
src/engine/Uno.ProjectFormat/PropertyDefinitions.cs

Xcode project generated by Uno now using `LaunchScreen.storyboard` instead of LaunchImages to comply with new rules from Apple. More info: https://developer.apple.com/news/?id=03042020b
We also bump minimal ios version to ver 9.0

Launch screen storyboard on iOS

---

lib/UnoCore/Targets/Android/Dependencies.uxl
lib/UnoCore/Targets/Android/app/build.gradle

This adds opt-in Kotlin support to Android Gradle projects.
1) Add Kotlin-files using UXL:
```
<CopyFile Condition="ANDROID" JavaFile="org/foo/Bar.kt" />
```
2) Pass `-DKOTLIN` to enable Kotlin support:
```
uno build android -DKOTLIN
```

Android: opt-in Kotlin support

---

lib/FuseJS.Transpiler/src/package-lock.json

This upgrades minimist to silence security warning in GitHub.
I tried rebuilding the minified JavaScript after upgrading, but `server.min.js` came out identical as before. No problem.

FuseJS.Transpiler: upgrade to minimist 1.2.5

---

lib/UnoCore/Source/Uno/Graphics/GraphicsController.uno

This method is used by Fuse Studio and needs to be public.

UnoCore: make GraphicsController.UpdateBackbuffer() public

---

src/engine/Uno.ProjectFormat/PropertyDefinitions.cs

This will use the version number specified in package.json, if available,
when Uno is invoked via a npm-script, unless an explicit version number was
specified in the project file or on the command-line.
With this, we no longer need Bash to forward the version number from
package.json onto Uno in a cross-platform way. This should make it a little
bit easier to maintain Uno packages using NPM.
See package.json in Fuselibs for an example.

Uno.ProjectFormat: use $npm_package_version as default version

---

disasm.sln
src/disasm/.gitignore
src/disasm/Uno.Disasm/Uno.Disasm.csproj

This moves the optional disasm.sln file up to the root directory of the
repository, where our other solution files also live.

move disasm.sln to root

---

lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist

Now you can add `NSFaceIDUsageDescription` on your `iOS Plist` attribute in the `unoproj`

Add FaceID usage description

---

lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml

Some Android app stores require us to explicitly define which features our app may use, I've added the common ones but more can be found here: https://developer.android.com/guide/topics/manifest/uses-feature-element
Usage
The boolean is used to describe if the feature is mandatory of your app.
Read more here: https://developer.android.com/guide/topics/manifest/uses-feature-element
```
"Android": {
"UsesFeatures": {
"AndroidHardwareLocation": false,
"AndroidHardwareLocationGPS": false,
"AndroidHardwareLocationNetwork": false,
"AndroidHardwareCamera": false,
"AndroidHardwareCameraAutofocus": false,
"AndroidHardwareMicrophone": false,
"AndroidHardwareTelephony": false,
"AndroidHardwareScreenPortrait": false,
"AndroidHardwareScreenLandscape": false,
"AndroidSoftwareWebview": false,
},
``` …

Android - Added Uses Features

---

src/compiler/Uno.Compiler.API/Domain/IL/EntityStats.cs
src/compiler/Uno.Compiler.Core/Syntax/Builders/TypeBuilder.cs
src/compiler/Uno.Compiler.Core/Syntax/Compilers/FunctionCompiler.cs
src/compiler/Uno.Compiler.Core/Syntax/Generators/Passes/ShaderProcessor.cs

Attempt to lazy-compile when encountering functions that aren't compiled in
ShaderProcessor. This can happen when an up-to-date version of a function's
assembly can be loaded from disk.
Before #282 this bug triggered only on methods pre-compiled in Uno.Runtime.Core.dll,
and after the bug started triggering on any method from another package.
This PR should fix the bug for all methods.

Compiler: fix bug/regression with incremental .NET builds

---

lib/UnoCore/Backends/CPlusPlus/CPlusPlus.uxl
lib/UnoCore/Backends/CPlusPlus/Uno/Memory.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/Memory.h
lib/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/ObjectModel.h
lib/UnoCore/Backends/CPlusPlus/Uno/Reflection.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/_config.h
lib/UnoCore/Targets/Native/natvis/uno.natstepfilter
src/compiler/Uno.Compiler.Backends.CPlusPlus/CppBackend.cs
src/compiler/Uno.Compiler.Backends.CPlusPlus/CppWriter.cs

This deprecates a superfluous macro and comes with some syntactical improvements to core C++ APIs.

C++ API clean-ups

---

.appveyor.yml
.travis.yml
lib/Uno.Net.Sockets/Tests/Socket.Test.uno
scripts/pack.sh

This upgrades to a newer Ubuntu image on Travis CI.
This fixes some issues and we're now able to run tests on Linux also, not only build them.

Upgrade to Ubuntu Bionic Beaver

---

lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/HttpRequest.java
lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/UploadTask.java

Install `HttpResponseCache` when we set `setCaching` to `true` on `HttpRequest.java`

Make url response cache functional on Android

---

Makefile
README.md
docs/build-instructions.md

This enables `make install` on all platforms (via `npm link`) and updates documentation.

Make install

---

.travis.xcconfig
.travis.yml
lib/UnoCore/Source/Uno/Platform/WindowBackend.uno
lib/UnoCore/Source/Uno/Platform/Xli/XliWindow.uno
scripts/test.sh
src/test/runner/TestProjectRunner.cs

This builds our code for iOS on Travis CI.
This also disables `dotnet` and `native` builds on macOS.
Rationale: `dotnet` is already being tested on Windows and `native` on Linux and Windows, and running more builds requires more time and resources. I think we can test these targets less frequently on macOS and still live comfortably.

Travis: iOS build

---

lib/UnoCore/Backends/CIL/CIL.uxl
lib/UnoCore/Backends/CPlusPlus/CPlusPlus.uxl
lib/UnoCore/Backends/CPlusPlus/Uno.cpp.uxl
lib/UnoCore/Backends/CPlusPlus/Uno/Support.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/Support.h
lib/UnoCore/Backends/CPlusPlus/Uno/XliInterop.h
lib/UnoCore/Backends/CPlusPlus/Uno/_config.h
lib/UnoCore/Targets/Native/Native.uxl
lib/UnoCore/UnoCore.unoproj

This removes legacy code from 2.0.
Fuselibs and other things I have tried still compile fine because these APIs are not used directly.

C++ clean-up

---

package-lock.json
package.json
scripts/pack.sh
scripts/restore.js
src/runtime/mac/app-mac.csproj
src/runtime/mac/packages.config
src/tool/engine/Uno.Build.csproj
src/tool/engine/packages.config

This switches to a new [xamarin-mac](https://www.npmjs.com/package/@fuse-open/xamarin-mac) package from NPM.

Replace xamarin-mac

---

lib/UnoCore/Source/Uno/Random.uno

UnoCore: use correct return type on Random.NextDouble()

---

lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist

Starting iOS 11, we have to add another Plist property `NSLocationAlwaysAndWhenInUseUsageDescription` when using geolocation continuously on foreground and background. More info [here](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocationalwaysusagedescription?language=objc)
this is a fix for the issue: https://github.com/fuse-open/fuselibs/issues/1128

iOS Plist add definition for location usage description

---

src/engine/Uno.Build/Stuff/StuffWebClient.cs

This makes sure we use TLS 1.2 when communicating with NuGet, because
NuGet recently dropped support for TLS 1.0 and 1.1.
If upgrading your Uno installation is inconvenient, it is possible to
enable TLS 1.2 for older Uno versions in the Windows Registry.
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:64
reg add HKLM\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 /v SystemDefaultTlsVersions /t REG_DWORD /d 1 /f /reg:32
https://devblogs.microsoft.com/nuget/nuget-org-will-permanently-remove-support-for-tls-1-0-and-1-1-on-june-15th/
https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

Hotfix: use TLS 1.2

---

lib/UnoCore/Source/Uno/AttributeTargets.uno
lib/UnoCore/Source/Uno/Reflection/TypeAliasAttribute.uno
lib/UnoCore/UnoCore.unoproj
src/compiler/backend/cil/CilBackend.cs
src/compiler/backend/cil/CilGenerator.Generate.cs

This will emit assembly attributes containing information about how UnoCore types map to .NET Framework types, when `REFLECTION` is defined. This is helpful to make the implementation of Fuse Simulator more robust.

.NET type aliases

---

docs/command-line-reference.md
src/test/runner/TestOptions.cs
src/test/runner/TestProjectRunner.cs
src/tool/cli/Projects/BuildCommand.cs
src/tool/cli/Projects/Clean.cs
src/tool/cli/Projects/Test.cs
src/tool/cli/System/Open.cs

This adds a `--gen-only` switch for `uno build` and `uno test` commands, and updates documentation.

CLI: add --gen-only

---

lib/Uno.Graphics.Utils/Cpp/CppTexture.uno
lib/UnoCore/Backends/CPlusPlus/Uno.cpp.uxl
lib/UnoCore/Backends/CPlusPlus/Uno/GLHelper.h
lib/UnoCore/Backends/CPlusPlus/Uno/Support.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/_config.h
lib/UnoCore/Source/OpenGL/GL.uno
lib/UnoCore/UnoCore.unoproj

We want to eliminate legacy C++ libraries eventually in v2.X, and this
is a step in that direction.

UnoCore: replace legacy includes

---

src/runtime/mac/UnoGLView.cs

Apparently all OpenGL apps powered by Mono on Mac stopped rendering if
built on a machine with Xcode 10 (or newer) installed.
Xcode 9.4 on macOS High Sierra is the last known to work configuration,
and apps built on this configuration would still work fine on newer
macOS and Xcode, it sounds like.
This fixes OpenGL rendering in apps built with Xcode 10 (macOS Mojave)
and newer.
https://github.com/xamarin/xamarin-macios/issues/4959

Mac: fix Xcode 10 regression

---

lib/UnoCore/Source/Uno/IO/Bundle.uno

This adds some more debug-info if we get problems with assembly loading.

UnoCore: handle exception in Bundle.GetAssembly()

---

src/tool/config/UnoConfig.cs
src/tool/config/UnoConfigFile.cs
src/tool/project/Project.cs

Reload config files when changed on disk, or every five seconds.
The purpose of the five seconds test is to avoid potential bugs caused by changes in directory structure, i.e. adding or removing config files, that are not being detected by our first test.
The PR fixes a bug in Fuse Studio.

Reload config files

---

src/tool/engine/BuildDriver.cs
src/tool/engine/BuildTarget.cs
src/tool/engine/Targets/AndroidBuild.cs
src/tool/engine/Targets/DocsBuild.cs
src/tool/engine/Targets/DotNetBuild.cs
src/tool/engine/Targets/MetadataBuild.cs
src/tool/engine/Targets/NativeBuild.cs
src/tool/engine/Targets/PInvokeBuild.cs
src/tool/engine/Targets/PackageBuild.cs
src/tool/engine/Targets/iOSBuild.cs

This returns the prefix that should be used when looking up properties in the project file, for example 'iOS' in 'iOS.Defines'.
Fixes #359.

Add BuildTarget.ProjectGroup property 

---

lib/UnoCore/Targets/Android/Android.uxl

This fixes the following error when building in release configuration.
BUILD SUCCESSFUL in 10s
31 actionable tasks: 7 executed, 24 up-to-date
The system cannot find the file specified.
(unknown): E0200: android build failed

Android: fix AAB filename

---

lib/Uno.Net.Sockets/Socket.uno
lib/UnoCore/Source/Uno/Guid.uno

This fixes compile-time warnings seen when building for iOS using latest version of Xcode.

 Fix compile-time warnings on iOS

---

lib/Uno.Permissions/Permissions.uno

A fork of this package (Fuse.Android.Permissions) is being merged into
Fuselibs (https://github.com/fuse-open/fuselibs/pull/1387).
Please move to that package instead.

Uno.Permission: deprecate all members

---

lib/UnoCore/Targets/iOS/run.sh

Before it was important to install the beta version because a needed
fix was only included in beta version (related to deploying apps on
a recent version of iOS I believe). This fix is now included in recent
stable versions of ios-deploy so we can safely drop the beta-tag.

iOS: recommend latest version of ios-deploy (not beta)

---

lib/Uno.Testing/RemoteRunner.uno
lib/UnoCore/Backends/CPlusPlus/Uno/Support.cpp
lib/UnoCore/Backends/CPlusPlus/Uno/_config.h
lib/UnoCore/Source/OpenGL/GL.uno
lib/UnoCore/Source/OpenGL/GLDebugLayer.uno
lib/UnoCore/Source/Uno/Diagnostics/Debug.uno
lib/UnoCore/Source/Uno/Diagnostics/Log.uno
lib/UnoCore/Source/Uno/Graphics/OpenGL/GLHelper.uno
lib/UnoCore/Source/Uno/Platform/CoreApp.uno
lib/UnoCore/UnoCore.unoproj
src/compiler/core/Syntax/Compilers/FunctionCompiler.Statements.Statement.cs
src/runtime/mac/MonoMacEnums.cs
src/runtime/mac/UnoGLView.cs
tests/src/StringBuilderBenchmark/App.uno

This adds a new Log class with a cleaner interface to replace the old
Debug class in Uno.Diagnostics.
Also deprecates legacy assert-statements and related functionality in
Uno.Diagnostics.Debug.

UnoCore: new Log class and deprecate assert-statements

---

lib/UnoCore/Source/Uno/Platform/iOS/Application.uno
lib/UnoCore/UnoCore.unoproj

This adds missing files to the project (after #363) and silences a compile-time warning when building for iOS.

UnoCore: missing files and iOS warning

---

src/compiler/backend/unodoc/ViewModels/MetaData/CommentViewModel.cs

Now the UnoDoc backend no longer randomly drops `@seealso` info from
generated JSON-files.
Closes #159
Closes #38

Fix race condition in UnoDoc backend

---

src/compiler/backend/unodoc/UnoDocBackend.cs

"indicies" is a mistake, so let's fix this typo while at it.

unodoc: fix typo in output folder

---

src/runtime/win/MainForm.cs
src/runtime/win/OpenTK/GL.cs

Some minor clean-ups to our .NET app-loader for Windows.

app-win: print warning and minor clean-ups

---

.appveyor.yml
docs/command-line-reference.md
src/runtime/generic/app-generic.csproj
src/runtime/mac/app-mac.csproj
src/runtime/win/app-win.csproj
src/tool/cli/Packages/Doctor.cs
src/tool/cli/Projects/BuildCommand.cs
src/tool/cli/Projects/Clean.cs
src/tool/cli/Projects/NoBuild.cs
src/tool/cli/Projects/Test.cs
src/tool/project/Project.cs
src/tool/project/PropertyDefinitions.cs

This makes the configuration part of the build output directory
lower-case, now making all path components of the default build
output directory lower-case.
Some users would argue that all lower-case directories appear more
modern, and look more familiar to users coming from other tooling.
Also, it's not a bad thing to update one's appearance once in a while,
and since we're preparing our next major release this seems like good
timing.
Please note that this is a breaking change (on case-sensitive
file-systems), though unlikely to affect users in practice (since
the majority of our audience are likely users of case-insensitive
file-systems, and it is rarely necessary to deal with your output
directory directly).

Make configuration directory lower-case

---

tests/src/UnoTest/General/Arrays.uno

This fixes deprecation warnings in tests after assert-statements were
deprecated in #375.

UnoTest: fix deprecation warnings

---

lib/UnoCore/Source/Uno/Diagnostics/Debug.uno

This forwards log-messages from the legacy Debug class to the new
Log class.

UnoCore: forward log to Log class

---

lib/UnoCore/Targets/iOS/@(Project.Name).xcodeproj/project.pbxproj

This fixes building for Simulator in Xcode 12, and also when using
latest Cocoapods v1.17.
* Exclude arm64 to avoid error about missing architectures when using
Xcode 12.
* Exclude i386 to avoid error about missing architectures when using
Cocoapods v1.17.
Closes #364

iOS: fix building for Simulator in Xcode 12

---

src/common/Logging/Log.cs
src/common/Logging/LogState.cs

This will show the last line of verbose output when logging in compact
mode (default), making things slightly more interesting and easier to
see what is happening during time consuming native builds for example.

common: show last line of verbose output in log

---

src/common/Diagnostics/PlatformDetection.cs

Uno will now report correct macOS version on Big Sur (11.x).
Uno version 2.0.0-beta.10 (dev-build) macOS 11.2 x86_64 N/A
Compare with before this patch:
Uno version 2.0.0-beta.10 (dev-build) macOS 10.16 x86_64 N/A
Also, check ARM architecture (Apple Silicon).

common: improve macOS version detection

---

lib/UnoCore/Targets/Android/Android.uxl

Google Play will require this version from August 2021.
https://developer.android.com/distribute/best-practices/develop/target-sdk#pre11

Android: upgrade build tools and target SDK version

---

README.md
docs/command-line-reference.md
lib/UnoCore/Targets/iOS/build.sh
lib/UnoCore/Targets/iOS/run.sh
src/tool/engine/BuildTargets.cs
src/tool/engine/Targets/iOSSimulatorBuild.cs
src/tool/engine/Uno.Build.csproj

This adds a new build target specifically for the iOS Simulator, so we
can easily build and run apps without going via Xcode.
Example:
uno build ios-sim --run

Add ios-sim build target

---

lib/UnoCore/Targets/iOS/.gitignore
lib/UnoCore/Targets/iOS/@(Project.Name).xcodeproj/project.pbxproj
lib/UnoCore/Targets/iOS/MetalANGLE.stuff
lib/UnoCore/Targets/iOS/MetalANGLE.uxl
lib/UnoCore/Targets/iOS/Uno-iOS.uxl
lib/UnoCore/Targets/iOS/Uno-iOS/AppDelegate.h
lib/UnoCore/Targets/iOS/Uno-iOS/AppDelegate.mm
lib/UnoCore/Targets/iOS/Uno-iOS/Context.h
lib/UnoCore/Targets/iOS/Uno-iOS/Context.mm
lib/UnoCore/UnoCore.unoproj
lib/UnoCore/prebuilt/uno-base.uxl

This adds opt-in support for rendering using the Metal graphics API via
MetalANGLE, a framework implementing OpenGLES APIs on top of Metal.
Use this to avoid referencing deprecated OpenGLES.framework on iOS.
* Pass `-DMETAL` to activate. E.g.: `uno build ios -DMETAL`.
* Pass `-DIOS_SIMULATOR` if you want to use iOS Simulator, to make sure
the right version of MetalANGLE.framework is used, or use the new
`ios-sim` build target (#395).
Closes #320

iOS: Metal graphics support

---

src/tool/engine/BuildDriver.cs
src/tool/engine/Targets/AndroidBuild.cs
src/tool/engine/Targets/DotNetBuild.cs
src/tool/engine/Targets/NativeBuild.cs
src/tool/engine/Targets/iOSBuild.cs

This is to avoid unintentional defines.

engine: make target defines explicit

---

lib/UnoCore/Source/Uno/Threading/Thread.uno
lib/UnoCore/Targets/Android/Uno/EntryPoints.cpp

Handle more C++ exceptions to make it easier to spot crashes on startup or in background threads.

Handle C++ exceptions

---

README.md
docs/command-line-reference.md
lib/UnoCore/Targets/Android/app/build.gradle
lib/UnoCore/Targets/Android/run.bat
lib/UnoCore/Targets/Android/run.sh
src/tool/cli/Android/LaunchApk.cs
src/tool/engine/Adb/AdbRunner.cs
src/tool/engine/BuildTargets.cs
src/tool/engine/Targets/AndroidEmulatorBuild.cs
src/tool/engine/Uno.Build.csproj

This adds a new build target specifically for emulators (x86_64).
While the regular `android` target builds ARM code by default (not
compatible with emulators), this one builds x86_64 code and makes sure
we run resulting apps on an emulator.
Example:
uno build android-emu --run
Similar to #395

Add android-emu build target

---

lib/UnoCore/Targets/Android/gradle/wrapper/gradle-wrapper.properties

This makes it possible to build on machines with JDK14 installed.
https://github.com/fuse-x/studio/issues/22

Android: upgrade to Gradle v6.9.2

---

.unoconfig

iPhone 13 Simulator is included with Xcode 13.

iOS: use iPhone-13 as default Simulator device

---

lib/UnoCore/Source/Uno/Long.uno

Seen when building using Xcode 13:
Implicit conversion loses integer precision: 'long long' to 'int'

iOS: silence C++ warning

---

lib/UnoCore/Targets/iOS/@(Project.Name).xcodeproj/project.pbxproj
lib/UnoCore/Targets/iOS/run.sh

This silences some warnings seen when building for iOS using Xcode 13.
This fixes a bug where the simulator device isn't picked up from
.unoconfig as expected.

Small iOS fixes

---

lib/UnoCore/Source/Uno/Threading/Thread.uno

This fixes the following error when running 'npm test android':
error: member access into incomplete type 'g::Uno::Exception'

Uno.Threading: fix C++ error

---

src/compiler/backend/unodoc/Uno.Compiler.Backends.UnoDoc.csproj
src/compiler/backend/unodoc/packages.config
src/compiler/foreign/Uno.Compiler.Foreign.csproj
src/compiler/foreign/packages.config
src/disasm/wpf/disasm-wpf.csproj
src/disasm/wpf/packages.config
src/tool/engine/Uno.Build.csproj
src/tool/engine/packages.config
src/tool/project/Uno.ProjectFormat.csproj
src/tool/project/packages.config

This fixes potential security vulnerabilities.
Newtonsoft.Json prior to version 13.0.1 is vulnerable to Insecure
Defaults due to improper handling of StackOverFlow exception (SOE)
whenever nested expressions are being processed. Exploiting this
vulnerability results in Denial Of Service (DoS), and it is
exploitable when an attacker sends 5 requests that cause SOE in time
frame of 5 minutes. This vulnerability affects Internet Information
Services (IIS) Applications.

upgrade Newtonsoft.Json to v13.0.1

---

lib/UnoCore/Targets/Android/@(Java.PackageDirectory)/@(Activity.Name).java

This fixes a problem where an external library (PickImage) doesn't
function correctly.
Also fixes a similar problem in onRequestPermissionsResult().

Android: add missing super-call in onActivityResult()

---

lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/gitignore
lib/UnoCore/UnoCore.unoproj

This makes it easier to add the generated Android project in Git,
without including build artifacts from Gradle etc.

Android: add gitignore file

---

lib/UnoCore/Targets/Android/Android.uxl
lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml

This makes it possible to add more attributes to the manifest element.
Needed to integrate a thirdparty library in Fuselibs.
Also adds AndroidManifest.ApplicationAttribute and
AndroidManifest.ActivityAttribute for application and activity elements.

Android: add AndroidManifest.ManifestAttribute for UXL

---

lib/UnoCore/android/dependencies.uxl

These packages are no longer needed since apps still build fine without.

Android: drop legacy packages

---

lib/UnoCore/android/app/src/main/AndroidManifest.xml

This is required on Android 12 and can be configured by setting
Android.Exported to true/false in your unoproj file.

Android: add android:exported attribute

---

src/common/Logging/Log.cs

Fixes subtle cases of extraneous newlines in log output.

Log: trim lines passed as object

---

lib/UnoCore/UnoCore.unoproj

This fixes build errors when archiving in Xcode, regressed in commit
59300eb27da39eb955de7625e85c155bebbef00c.

iOS: restore build settings for Context.mm

---

src/compiler/core/Syntax/Builders/TypeBuilder.cs
src/compiler/foreign/ForeignCPlusPlusPass.cs
src/compiler/foreign/ObjC/Conversion.cs

These are not used by the code and cause build errors on .NET 6.

compiler: drop unused using statements

---

lib/UnoCore/android/android.uxl
lib/UnoCore/android/dependencies.uxl

Targetting API 31 (Android 12) by default because this will be required by Google Play Store starting in November 2022.
Also upgrading dependencies to more recent versions that require API 31.

Android: Upgrade to API 31

---

lib/UnoCore/android/@(Java.PackageDirectory)/@(Activity.Name).java

This function was missing the super call and doing this fixes a linter warning seen in Android Studio.
Also fix-up braces and whitespace, and remove comments.

Android: call super.onNewIntent()

---

.appveyor.yml

We're still using the old lock-file version so this will avoid seeing warnings in the build log.

appveyor: use nodejs v14

---

lib/UnoCore/android/android.uxl
lib/UnoCore/android/gradle.properties

This UXL element makes it possible to output project-specific information in the gradle.properties file.
Example.uxl:
```xml
<Require Gradle.Properties>
<![CDATA[
org.gradle.jvmargs=-Xmx1536M \
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED \
--add-opens=java.base/java.lang=ALL-UNNAMED \
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
--add-opens=java.base/java.io=ALL-UNNAMED \
--add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED
]]>
</Require>
```

Android: Add Gradle.Properties element

---

.appveyor.yml
src/runtime/generic/app-generic.csproj
src/runtime/mac/app-mac.csproj
src/runtime/win/app-win.csproj
src/tool/project/PropertyDefinitions.cs

This reverses the last two path components of Output Directory, so that Configuration comes before Target, e.g.
project/build/debug/android/
This is similar to how it is in .NET 6.0 and feels more modern.

update default output directory (beta-3.0)

---

scripts/pack.sh
scripts/restore.js

* Append /net6.0 to paths to make package size small again
* Remove *.mdb reference since not relevant on .NET 6.0

update pack/restore for net6.0 (beta-3.0)

---

src/tool/engine/Packages/LibraryBuilder.cs
src/tool/engine/Packages/LibraryProject.cs
src/tool/engine/Packages/PackageFile.cs
src/tool/engine/Packages/PackageSearchPaths.cs

Before when building libraries, output files were placed inside a directory named after the current version of the library, e.g.
lib/build/UnoCore/1.2.3/
This is a relic from a time where it was possible to install multiple versions of the same library side by side using Uno Package Manager.
Uno Package Manager was removed in favor of NPM in 2019, so we no longer have this requirement and can remove the last directory part, e.g.
lib/build/UnoCore/
We should still be able to load libraries built by older versions of Uno using the version directory.

remove VersionDirectory from libraries (beta-3.0)

---

.appveyor.yml
.unoconfig
lib/UnoCore/cil/exe.cil.uxl
scripts/restore.js
src/runtime/mac/AppDelegate.cs
src/runtime/mac/Info.plist
src/runtime/mac/MonoMacEnums.cs
src/runtime/mac/MonoMacGL.cs
src/runtime/mac/MonoMacGraphicsContext.cs
src/runtime/mac/MonoMacPlatformWindow.cs
src/runtime/mac/Program.cs
src/runtime/mac/UnoGLView.cs
src/runtime/mac/app-mac.csproj

Getting closer to running .NET 6.0 apps on macOS.
* Use generic app loader for now so we can run tests.

runtime/mac: switch to Microsoft.macOS.SDK (beta-3.0)

---

scripts/pack.sh

* macOS binaries are too big and will be provided by other means.
This brings the total package size down to around 4MB.

pack: remove native macOS binaries (beta-3.0)

---

lib/Uno.Graphics.Utils/Uno.Graphics.Utils.unoproj

This library is being removed in https://github.com/fuse-open/fuselibs/pull/1458.

Uno.Graphics.Utils: drop reference to Experimental.TextureLoader (beta-3.0)

---

src/compiler/core/IL/Building/Functions/Lambdas/ClosureConvertFunction.cs
src/compiler/core/Syntax/Builders/TypeBuilder.Parameterize.cs
tests/src/UnoTest/General/Lambdas.uno

This updates ClosureConvertFunction to generate valid code when lambdas are used inside generic classes.
Generic classes need a definition object and one or more parameterized objects pointing back to their definition. Essentially, we're now creating copies of relevant objects where necessary, so that other parts of the comiler can work correctly.

compiler: support lamdas in generic classes

---

lib/UnoCore/src/Uno/Diagnostics/Log.uno

This makes it possible to pass arguments that are not strings to our logging methods.

UnoCore: add object overloads in Uno.Diagnostics.Log

---

.unoconfig

iPhone 14 Simulator is included with Xcode 14.

iOS: use iPhone-14 as default Simulator device

---

src/tool/config/UnoConfig.cs

This removes IsRoot and SkipIfRoot, which had some strange effects where we've ended up patching the unoconfig-file after install, in e.g. https://github.com/fuse-open/fuse-sdk/blob/master/scripts/restore.js
Let's try removing these properties for v3.0 and see if we can get rid of that unoconfig-patching.

unoconfig: remove *Root properties (beta-3.0)

---

lib/UnoCore/src/Uno/Compiler/CallerMemberNameAttribute.uno
lib/UnoCore/src/Uno/IO/Bundle.uno
src/compiler/core/IL/Utilities/Essentials.cs
src/compiler/core/IL/Validation/ILVerifier.cs
src/compiler/core/Syntax/Compilers/FunctionCompiler.OverloadResolver.cs

* In the Bundle class, deprecate the PackageName property and add Name instead.
* Deprecate the CallerPackageName attribute and add CallerBundleName instead.
* Update the compiler to use the new attribute.
* Update related variable names.
Related to #440

UnoCore: rename PackageName members (beta-3.0)

---

.unoconfig
src/tool/engine/Libraries/BundleCache.cs
tests/src/.unoconfig

We want to stop saying "packages" when referring to Uno libraries (#440), so this renames the following unoconfig properties:
* Packages.SearchPaths -> SearchPaths
* Packages.SourcePaths -> SearchPaths.Sources
(The old names are deprecated but still work)

unoconfig: rename Packages.* properties (beta-3.0)

---

lib/Uno.Collections/tests/Uno.Collections.Test.unoproj
lib/Uno.Data.Json/tests/Uno.Data.Json.Test.unoproj
lib/Uno.Data.Xml/tests/Xml.Test.unoproj
lib/Uno.Net.Http/tests/Http.Test/Http.Test.unoproj
lib/Uno.Net.Http/tests/HttpStatusCodeTester/HttpStatusCodeTester/HttpStatusCodeTester.unoproj
lib/Uno.Net.Sockets/tests/Uno.Net.Sockets.Test.unoproj
lib/Uno.Testing/tests/Uno.Testing.Test.unoproj
lib/Uno.Threading/tests/Threading.Test.unoproj
lib/UnoCore/tests/UnoCore.Test.unoproj
src/test/data/FirstTest/FirstTest.unoproj
src/tool/engine/BuildDriver.cs
src/tool/project/Project.cs
src/tool/project/UnoprojDocument.cs
src/tool/project/UnoprojParser.cs
src/tool/project/UnoprojSerializer.cs
tests/libtest/libtest.unoproj
tests/src/AutoReleasePoolStructTest/AutoReleasePoolStructTest.unoproj
tests/src/Benchmark/Benchmark.unoproj
tests/src/BundleApp/BundleApp.unoproj
tests/src/BundleRecursive/BundleRecursive.unoproj
tests/src/CFileIncludeTest/CFileIncludeTest.unoproj
tests/src/ForeignCPlusPlusTest/ForeignCPlusPlusTest.unoproj
tests/src/ForeignJavaTest/ForeignJavaTest.unoproj
tests/src/ForeignObjCTest/ForeignObjCTest.unoproj
tests/src/FullPathApp/FullPathApp.unoproj
tests/src/SwiftFileIncludeTest/SwiftFileIncludeTest.unoproj
tests/src/TransitiveApp/TransitiveApp.unoproj
tests/src/UXTest/UXTest.unoproj
tests/src/UnoTest/UnoTest.unoproj

Same motivation as #451, #452 and #453. Old names are deprecated but still work.
* Update related member names in the compiler.
* Update project files.

unoproj: rename "Packages" -> "References" (beta-3.0)

---

lib/Uno.Net.Http/ios/HttpRequest.mm
lib/UnoCore/cpp/Uno/Uno.h
lib/UnoCore/ios/@(Project.Name)/@(Project.Name)-Prefix.pch
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/uObjC.String.h
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/uObjC.UnoArray.h
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/uObjC.UnoArray.mm
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/uObjC.UnoObject.mm
lib/UnoCore/src/Uno/Platform/iOS/Display.mm
lib/UnoCore/src/Uno/Platform/iOS/Window.mm

Include uno.h instead and fix the deprecation warning in Uno/Uno.h.

iOS: replace Uno/Uno.h includes

---

lib/UnoCore/cpp/Uno/ObjectModel.cpp
lib/UnoCore/cpp/Uno/ObjectModel.h

Deprecated since before version 1.0.

C++: remove legacy uFreeCStr() (beta-3.0)

---

src/compiler/backend/cpp/DeclarationComparer.cs
src/compiler/backend/cpp/IncludeResolver.cs

Use DeclarationComparer to sort declarations before being emitted into source files to make sure preprocessor directives (lines starting with '#') come out first.
This solves a problem where ManualTestingApp in Fuselibs fails to build for Android since our last beta release, because some declarations come out before includes. This might have regressed with changes in #456.

C++-backend: use a comparer when sorting in IncludeResolver (beta-3.0)

---

src/tool/engine/BuildDriver.cs

In 1e13ffc we assumed that TEST was already defined when building via `uno test`, but it was not, so this commit defines it now.
It's possible to pass custom defines if necesary, e.g. for old code: `uno test -DUNO_TEST`.

uno test: define TEST (beta-3.0)

---

docs/configuration.md
scripts/clean.sh
src/test/compiler-test/CompilerTestRunner.cs
src/tool/cli/Building/Create.cs
src/tool/cli/Building/Update.cs
src/tool/config/UnoConfig.cs
src/tool/engine/Libraries/LibraryBuilder.cs
src/tool/engine/Libraries/LibraryDoctor.cs
src/tool/project/Project.cs

Like #453, this renames another unoconfig property:
* Packages.Defaults -> References.Default
(The old name is deprecated but still works)
Also includes updates to LibraryBuilder and LibraryDoctor, missed in
e13bddaa9f4c69c7dda12991c77dbb254496ae89.
* Update unoconfig property names
* Clean nupkg and tgz files
* Update unoconfig property names
* Restructure the document a little

unoconfig: {Packages -> References}.Default (beta-3.0)

---

lib/UnoCore/android/android.uxl
lib/UnoCore/cpp/config.cpp.uxl
lib/UnoCore/ios/ios.uxl
lib/UnoCore/native/native.uxl
lib/UnoCore/pinvoke/pinvoke.uxl
src/compiler/frontend/Xml/XmlPreprocessor.cs

Attribute values without quotes is not valid XML, confuses editors and syntax-highlighters, and should not have been supported.
This adds quotes to existing UXL files where quotes were previously missing, and modifies XmlPreprocessor to require quotes in version 3.0.

frontend: require XML attribute values to be quoted (beta-3.0)

---

index.d.ts
index.js
package.json
tests/node/uno.js

When installing fuse-sdk locally in an empty Node.js package, npm fails with an ENOENT error because the following file can't be found, at least on some systems (tested on MacBook Air M1 with npm v8.9.0):
[...]/node_modules/fuse-sdk/node_modules/@fuse-open/uno/bin/uno.js
(Installing fuse-sdk globally works fine, or installing @fuse-open/uno locally before installing fuse-sdk also works as a workaround.)
This patch is a step towards fixing the problem in fuse-sdk, and the idea is to "require" uno in fuse-sdk, rather than hardcoding its path.

export function to run Uno from JavaScript/TypeScript (beta-3.0)

---

lib/UnoCore/ios/run.sh

This will detect the first iPhone device when the preferred device isn't found in the list of supported devices, instead of aborting with error.

iOS: detect simulator device

---

lib/UnoCore/cpp/Uno/Uno.h
lib/UnoCore/ios/@(Project.Name).xcodeproj/project.pbxproj

* Silence warning about 'Run Script' will be run during every build
* Comment out #warning added in b2fad01, because warnings are seen even if no source files are including the deprecated header file

iOS: silence warnings

---

src/compiler/core/Syntax/Compilers/FunctionCompiler.Statements.Statement.cs
tests/src/UnoTest/General/TryCatch.uno

'assert' statements were turned into method calls to a method that was removed in 992b515, resulting in compile errors.
'assert' is still used in a few places, and this commit turns them into "if-test and throw" in debug builds (noop in release builds) to fix the compile errors.
assert VALUE;
becomes when compiled:
if (IS_DEBUG_BUILD && !VALUE)
throw new Uno.InvalidOperationException(
"Assertion failed: VALUE"
);

compiler: return "if-test and throw" when compiling 'assert' (beta-3.0)

---

src/compiler/backend/cpp/CppGenerator.cs
src/compiler/backend/cpp/DeclarationComparer.cs

This makes DeclarationComparer more robust and makes sure to use it when combining declarations in CppGenerator, missed in fa03654.
This fixes compile errors when compiling Android apps on macOS.

C++-backend: fix Android compile errors on macOS (beta-3.0)

---

package-lock.json
package.json
scripts/pack.sh
scripts/restore.js
src/tool/engine/Targets/Utilities/DevelopmentTeam.cs
src/tool/engine/Uno.Build.csproj

Xamarin.Mac isn't supported on .NET 6 (throws exception), blocking us from building iOS apps, so this commit removes the dependency.
Xamarin.Mac was used to access Xcode Developer Teams, so we need a way to replace this functionality. I have searched for a node module or a CLI that can replace it, without luck, so it looks like we'll need to implement a new tool to access Xcode Developer Teams at some point.

remove xamarin-mac dependency (beta-3.0)

---

src/compiler/core/Syntax/UxlProcessor.cs

We don't want to see the output from external tools. This is a follow-up from ccb50a4.

compiler: hide output from image converters (beta-3.0)

---

scripts/restore.js

This fixes an error seen when launcing Android apps on macOS.

restore: make sure the shell script is executable (beta-3.0)

---

src/common/Diagnostics/ProcessExtensions.cs

Avoid getting a callstack in the output when force quitting using CTRL + C keys on macOS Ventura.

common: swallow InvalidOperationException in KillTree() (beta-3.0)

---

src/compiler/api/Domain/AST/Members/AstClassMember.cs
src/compiler/backend/cil/CilType.cs
src/compiler/core/IL/Bytecode/BytecodeCompiler.Expression.cs
src/compiler/core/IL/Validation/ILVerifier.Member.cs

This removes an obsolete temp hack and addresses a few old TODOs.

compiler: remove temp hack and TODOs (beta-3.0)

---

lib/UnoCore/cpp/Uno/ObjectModel.cpp

This will raise assertion failure if any objects with incomplete v-tables are detected when DEBUG_UNSAFE is defined.

C++: verify v-tables (DEBUG_UNSAFE) (beta-3.0)

---

lib/UnoCore/cil/app.cil.uxl
lib/UnoCore/cil/mac-loader.stuff
lib/UnoCore/cil/test.cil.uxl
src/compiler/core/BuildEnvironment.cs
src/test/runner/ProjectDiscoverer.cs
src/tool/engine/BuildDriver.cs
src/tool/project/OutputType.cs

Some tests (several in Fuselibs) need a proper graphics context etc., so this adds a new "appTest" output type for tests to be run as apps.

project-format: add outputType.appTest (beta-3.0)

---

src/tool/engine/Libraries/LibraryProject.cs
src/tool/engine/Libraries/ManifestFile.cs

This file used to be called "package". We will fallback to the old name if "manifest" isn't found, to keep supporting libraries built by an older version of Uno.

engine: rename manifest file in libraries (beta-3.0)

---

lib/Uno.Net.Sockets/Dns.uno
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ForeignAnnotationAttribute.uno
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ForeignDataView.uno
lib/UnoCore/src/Uno/Compiler/ExportTargetInterop/Foreign/ForeignIncludeAttribute.uno
src/compiler/api/Domain/IL/Expressions/Expression.cs
src/compiler/api/Domain/IL/Expressions/NewArray.cs
src/compiler/api/Domain/IL/Expressions/NewObject.cs
src/compiler/backend/unodoc/Builders/Syntax/SyntaxGenerator.cs
src/compiler/core/IL/Validation/ILVerifier.cs
src/compiler/core/Syntax/Compilers/Extensions.cs
src/compiler/foreign/ForeignHelpers.cs
src/compiler/foreign/ForeignObjCPass.cs
src/compiler/foreign/Java/JavaClass.cs
tests/src/ForeignJavaTest/Args.uno
tests/src/ForeignJavaTest/Arrays.uno
tests/src/ForeignJavaTest/Fields.uno
tests/src/ForeignJavaTest/Macros.uno
tests/src/ForeignJavaTest/Names.uno
tests/src/ForeignObjCTest/FileInclude.uno
tests/src/SwiftFileIncludeTest/SwiftFileIncludeTest.uno

This removes a bunch of redundant constructors from
ForeignIncludeAttribute and ForeignAnnotatonAttribute.
This makes it possible to accept an array of constants (or use params)
in attribute constructors, enabling us to make some code a bit nicer
(ForeignIncludeAttribute and ForeignAnnotatonAttribute).
* Implement NewArray.ConstantValue
* Modify Expression.ConstantString to serialize arrays (via ToString())
* Remove unused method in NewObject
* Remove redundant 'env' parameter in ForeignHelpers
* Update UnoDoc backend
This accepts ForeignInclude attributes on methods and types, instead of
just types. Specifying the ForeignInclude attribute on the method it is
used (rather than the whole type) makes things more coherent.
* Update existing ForeignInclude attributes in the code-base

accept ForeignInclude attributes on methods (beta-3.0)

---

src/compiler/core/Compiler.cs
src/compiler/core/IL/EntitySwapper.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CompileDraw.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CreateBlock.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CreateMetaProperty.cs
src/compiler/core/Syntax/Builders/BlockBuilder.FlattenType.cs
src/compiler/core/Syntax/Builders/BlockBuilder.cs
src/compiler/core/Syntax/Builders/BuildQueue.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateClass.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateDelegate.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateEnum.cs
src/compiler/core/Syntax/Builders/TypeBuilder.Parameterize.cs
src/compiler/core/Syntax/Builders/TypeBuilder.PopulateClass.cs
src/compiler/core/Syntax/Builders/TypeBuilder.cs
src/ux/markup/CompilerReflection/ILCache.cs

Extract BuildQueue from BlockBuilder and TypeBuilder to get better control over when different classes, functions, etc, are compiled, improving abilities when it comes to lazy compilation.

compiler: refactor build queue (beta-3.0)

---

.appveyor.yml
src/disasm/core/Uno.Disasm.csproj
src/disasm/wpf/disasm-wpf.csproj

Uno Disassembler seems to run fine again after this.
* AvalonEdit -> 6.3.0.90
* Newtonsoft.Json -> 13.0.2
Upgrading MahApps.Metro and ControlzEx gives exception on startup and
were rolled back again for now.
Get notified if we break the build. Disable warnings.

disasm: embed resources and upgrade packages (beta-3.0)

---

lib/UnoCore/android/android.uxl

Targeting API 33 (Android 13) by default because this will be required by Google Play Store starting in August 2023. More info: https://developer.android.com/google/play/requirements/target-sdk
Also, we are upgrading minimum API 19 (Android KitKat), This is necessary for compatibility with Firebase Messaging for Push Notification

Android: Upgrade to API 33 and Minimum to 19

---

lib/UnoCore/android/app/src/main/AndroidManifest.xml

On Android targeting API 30 or later, we need to specify in `AndroidManifest` package visibility needs for Google Maps so that in the `MapView` component when we click a marker, the options that will show up on the bottom right of the screen can be clickable and will be redirected to the Google Maps App (currently broken).
This issue has been reported on Slack.
More info about Package Visibility: https://developer.android.com/training/package-visibility/declaring

Register package visibility needs for google maps

---

src/test/runner/TestProjectRunner.cs
src/test/runner/UnoTest.cs

This restructures TestProjectRunner.cs a little to make it slightly cleaner and to early out before reaching _logger.ProjectEnded(tests) if the --build-only flag was passed.

uno-test: don't print stats with --build-only (beta-3.0)

---

lib/UnoCore/cil/run.bat
lib/UnoCore/cil/run.sh
scripts/test.sh
src/compiler/api/Domain/Graphics/Drawable.cs
src/compiler/core/Compiler.cs
src/compiler/core/IL/EntitySwapper.cs
src/compiler/core/IL/Testing/TestSetupTransform.cs
src/compiler/core/IL/Validation/ILVerifier.Type.cs
src/compiler/core/Syntax/Binding/NameResolver.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CompileDraw.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CreateBlock.cs
src/compiler/core/Syntax/Builders/BlockBuilder.CreateMetaProperty.cs
src/compiler/core/Syntax/Builders/BlockBuilder.FlattenType.cs
src/compiler/core/Syntax/Builders/BlockBuilder.cs
src/compiler/core/Syntax/Builders/BuildQueue.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateClass.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateDelegate.cs
src/compiler/core/Syntax/Builders/TypeBuilder.CreateEnum.cs
src/compiler/core/Syntax/Builders/TypeBuilder.Parameterize.cs
src/compiler/core/Syntax/Builders/TypeBuilder.PopulateClass.cs
src/compiler/core/Syntax/Builders/TypeBuilder.cs
src/compiler/core/Syntax/Compilers/FunctionCompiler.NameResolver.TypeExtension.cs
src/compiler/core/Syntax/Generators/DrawCallGenerator.cs
src/compiler/core/Syntax/UxlProcessor.cs
src/compiler/frontend/SourceReader.cs
src/ux/markup/CompilerReflection/ILCache.cs

Apps that are not console apps or tests should be run without using the
dotnet command on macOS.
This fixes errors with subsequent builds experienced when using the
dotnet backend on macOS (while running Fuselibs tests).
Make sure it still works when building the same projects a second time.
This fixes five problems experienced on subsequent builds using the
dotnet backend (regressed in 40403e7):
* Resolving an extension method
* Resolving the application constructor in TestTestupTransform
* Resolving sizeof expressions
* Resolving a type nested inside a generic type
* Validating a generic type argument
All problems were already fixed on the lazy branch so the fixes were
cherry-picked together with a few similar fixes.
This reverts commit 02f2177804edc94545318773244428af24ac46ff.

compiler: fix build queue regressions (beta-3.0)

---

.appveyor.yml
src/compiler/api/Domain/IL/Types/DataType.cs
src/compiler/core/BuildEnvironment.cs
src/compiler/core/CompilerOptions.cs
src/compiler/core/IL/Testing/TestSetupTransform.cs
src/compiler/core/IL/Utilities/ILFactory.cs
src/compiler/core/IL/Validation/ILVerifier.Type.cs
src/compiler/core/Syntax/Builders/BlockBuilder.PopulateBlock.cs
src/compiler/core/Syntax/Builders/BuildQueue.cs
src/tool/engine/BuildDriver.cs
src/tool/engine/BuildTarget.cs
src/tool/engine/Targets/DotNetBuild.cs

We want to make sure this feature keeps on working. This is the first
iteration and more updates are expected.
Pass -DLAZY to "uno build" to enable lazy compilation (experimental).
We've seen around 10x[1] speed-up on subsequent builds of a normal app
when lazy compilation is enabled, since there is minimal work to do
when most of the code is already built.
The feature is experimental for now, but we might want to take
advantage of this (e.g. in the Fuse X editor) when the feature
matures a bit more, to speed up loading times in a significant way
by prebuilding standard libraries (including Fuselibs), and better
caching.
1: More or less, depending on project size
This modifies the compiler to only compile something when it is needed
and not compiled before, rather than always compiling …

lazy compilation for .NET targets (beta-3.0)

---

package-lock.json
package.json
src/tool/engine/Targets/Generators/XcodeGenerator.cs
src/tool/engine/Targets/Utilities/DevelopmentTeam.cs
src/tool/engine/Targets/iOSBuild.cs
src/tool/engine/Targets/iOSSimulatorBuild.cs

This uses the native xcode-devteams utility to get information about Xcode developer teams and restores the functionality that was removed in ead12f8.

install xcode-devteams (beta-3.0)

---

src/test/runner/TestOptions.cs
src/test/runner/TestProjectRunner.cs
src/tool/cli/Building/Test.cs

Pass --clean or -z to clean the output directory when building tests, like the "uno build" command already supports.

uno test: add --clean parameter (beta-3.0)

---

src/tool/engine/Libraries/BundleCache.cs

This makes "uno config -l" list all libraries again, missed in fa61353.

engine: fix library enumerator in BundleCache (beta-3.0)

---

.appveyor.yml
docs/configuration.md
lib/UnoCore/android/android.uxl
lib/UnoCore/android/app/build.gradle
lib/UnoCore/android/build.bat
lib/UnoCore/android/build.sh
lib/UnoCore/android/dependencies.uxl
lib/UnoCore/android/gradle/wrapper/gradle-wrapper.properties

Requires JDK 17. Run `npm install android-build-tools@2.x -g` to update your configuration after installing JDK 17.
* gradle-plugin -> 8.1.0
* gradle-wrapper -> 8.2
* build-tools -> 33.0.1
* add namespace in build.gradle
* update configuration.md

android: upgrade to Gradle 8.2 (beta-3.0)

---

lib/UnoCore/android/app/src/main/AndroidManifest.xml

* Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported, and the value is ignored.
* android:extractNativeLibs should not be specified in this source AndroidManifest.xml file.

android: fix Gradle 8 warnings (beta-3.0)

---

lib/UnoCore/android/android.uxl
lib/UnoCore/android/app/build.gradle
lib/UnoCore/android/dependencies.uxl
lib/UnoCore/android/gradle.properties
lib/UnoCore/ios/@(project.name).xcodeproj/project.pbxproj
src/tool/project/PropertyDefinitions.cs

This commit bump minimum Android SDK now 21 and target SDK 34, and also upgrade Gradle version to 8.1.4 and more Kotlin Supports. 
This commit bump minimum iOS version to 13 and Swift version to 5.

Bump min version of Android and iOS and upgrade Kotlin and Swift version
