fuse-open/uno

- .teamcity_set_versions.sh
- scripts/common.sh
- scripts/pack.sh
Here's a few cleanups in the build-scripts.
> Script cleanups

- Library/Core/Uno.Data.Json/Source/JsonReader.uno
- Library/Core/Uno.Data.Xml/Source/XmlAttributeHandle.uno
- Library/Core/Uno.Data.Xml/Source/XmlNodeHandle.uno
- Library/Core/Uno.Data.Xml/Source/XmlNodeImpl.uno
- Library/Core/Uno.Data.Xml/Targets/CIL/Uno.Data.Xml.cil.uxl
- Library/Core/Uno.Data.Xml/Targets/CPlusPlus/Uno.Data.Xml.cpp.uxl
- Library/Core/Uno.Net.Http/Implementation/Xli/XliHttpEventHandler.h
- Library/Core/Uno.Net.Http/Implementation/Xli/XliHttpRequest.cpp.uxl
- Library/Core/Uno.Net.Http/Implementation/Xli/XliHttpRequest.uno
- Library/Core/UnoCore/Backends/CIL/CIL.uxl
Removes some unnecessary references to Uno.Platform and XliString..
> Standard lib clean-ups

- src/compiler/Uno.Compiler.Backends.CPlusPlus/Uno.Compiler.Backends.CPlusPlus.csproj
- src/compiler/Uno.Compiler.Frontend/Uno.Compiler.Frontend.csproj
- src/main/Uno.CLI/Uno.CLI.csproj
- src/ux/Uno.UX.Markup.AST/Tests/Uno.UX.Markup.AST.Tests.csproj
Here's a couple of patches to clean up the project files so [MonoDevelop][1]
won't keep automatically update them.
[1]: https://www.monodevelop.com/
> Monodevelop cleanups

- src/runtime/Uno.AppLoader-MonoMac/AppDelegate.cs
- src/runtime/Uno.AppLoader-MonoMac/Program.cs
- src/runtime/Uno.AppLoader-MonoMac/Uno.AppLoader-MonoMac.csproj
- src/runtime/Uno.AppLoader-MonoMac/UnoGLView.cs
- src/runtime/Uno.AppLoader-WinForms/Uno.AppLoader-WinForms.csproj
This just cleans up some warnings an needless using-statements.
> Apploader cleanups

- src/compiler/Uno.Compiler.API/Domain/IL/Members/Function.cs
- src/compiler/Uno.Compiler.Core/IL/Testing/TestSetupTransform.cs
Some improvements to TestSetupTransform in the compiler.
I just ran the fuselibs test suite to make sure things still work.
> Test transform improvements

- Library/Core/Uno.Threading/Implementation/Win32/Win32Helpers.uno
- Library/Core/UnoCore/Backends/CPlusPlus/Uno/WinAPIHelper.h
- Library/Core/UnoCore/Source/Uno/Threading/Thread.uno
This fixes compile-time issues with `WinAPIHelper.h` when working with fuselibs.
> Win32 fixes

- .gitignore
- .vscode/settings.json
I use Visual Studio Code a lot, and this file is useful for me.
I'm hoping it will be useful for other users too.
> Add Visual Studio Code workspace settings

- Library/Core/UnoCore/Targets/Android/Android.uxl
- Library/Core/UnoCore/Targets/Android/app/build.gradle
- src/compiler/Uno.Compiler.Core/Syntax/UxlProcessor.cs
Just some small clean-ups in the gradle build script.
> Android gradle cleanup

- Library/Core/UnoCore/Source/Uno/Matrix.uno
Just two simple clean-ups for the `Matrix` class in `UnoCore`.
> UnoCore: Matrix clean-ups

- Library/Core/UnoCore/Source/Uno/String.uno
This fixes several cases of double-copying strings via `char[]` on C++, and improves some formatting.
> String optimizations for C++

- LICENSE.txt
- src/GlobalAssemblyInfo.cs
Fusetools AS no longer owns or maintains this project, so it's time to update this information.
> update copyright info

- src/testing/Uno.TestRunner.BasicTypes/CommandLineOptions.cs
- src/testing/Uno.TestRunner.Loggers/ConsoleLogger.cs
These two patches will improve our test runner experience a little bit, IMO.
> Uno.TestRunner improvements

- lib/UnoCore/Targets/Android/Android.uxl
- lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
Some clean-ups/improvements to our NDK integration.
> Android NDK integration clean-ups

- lib/UnoCore/Source/Uno/String.uno
- lib/UnoCore/Source/Uno/Threading/Monitor.uno
- lib/UnoCore/Source/Uno/Threading/Thread.uno
Some small clean-ups in UnoCore, mainly for readability.
> UnoCore clean-ups

- lib/UnoCore/Targets/Android/Android.uxl
- lib/UnoCore/Targets/Android/app/build.gradle
- lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
- lib/UnoCore/Targets/Android/com/uno/CppManager.java
- lib/UnoCore/prebuilt/uno-base-pinvoke.uxl
- lib/UnoCore/prebuilt/uno-base.uxl
- src/engine/Uno.Build.Targets/Android/AndroidGenerator.cs
I think this makes more sense, improves consistency, and looks better IMO.
> Android: rename some build properties

- README.md
I noticed that the README Appveyor badge is broken. This seems to fix it.
> Fix Appveyor bagde

- Makefile
- scripts/pack.sh
Embed the commit SHA when releasing .NET assemblies, and clean up the pack script.
> Pack script tweaks

- scripts/pack.sh
This removes an unused variable and an unused file.
> pack.sh: remove dead-code

- lib/FuseJS.Transpiler/FuseJS.Transpiler.unoproj
- lib/Uno.Collections/Uno.Collections.unoproj
- lib/Uno.Data.Json/Uno.Data.Json.unoproj
- lib/Uno.Data.Xml/Uno.Data.Xml.unoproj
- lib/Uno.Net.Http/Uno.Net.Http.unoproj
- lib/Uno.Net.Sockets/Uno.Net.Sockets.unoproj
- lib/Uno.Permissions/Uno.Permissions.unoproj
- lib/Uno.Testing/Uno.Testing.unoproj
- lib/Uno.Threading/Uno.Threading.unoproj
- lib/UnoCore/UnoCore.unoproj
This updates meta data information in our Uno projects.
> set Fuse Open as publisher of Uno packages

- lib/UnoCore/Targets/Android/build.bat
- lib/UnoCore/Targets/Android/build.sh
- lib/UnoCore/Targets/Android/run.bat
- src/main/Uno.CLI/Android/AdbRunner.cs
- src/main/Uno.CLI/Android/LaunchApk.cs
This contains some fixes and improvements to our Build & Run functionality for Android.
> Android: build/run improvements

- README.md
- lib/Uno.Net.Sockets/Dns.uno
- lib/UnoCore/Source/Uno/IO/File.uno
- lib/UnoCore/Source/Uno/Long.uno
- lib/UnoCore/Source/Uno/ULong.uno
- lib/UnoCore/Targets/Native/CMakeLists.txt
- lib/UnoCore/prebuilt/uno-base.stuff
- lib/UnoCore/prebuilt/uno-base.uxl
This adds support for building native apps and running tests on Linux. Tested on Ubuntu 18.04 x86_64.
> Linux native build support

- bin/uno
- lib/UnoCore/Targets/Native/build.bat
- lib/UnoCore/Targets/Native/run.bat
> Script fixes

- lib/UnoCore/Backends/CPlusPlus/Uno/_main.cpp
- lib/UnoCore/Backends/CPlusPlus/Uno/_mainMobile.cpp
- lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
- lib/UnoCore/Targets/Native/CMakeLists.txt
- src/compiler/Uno.Compiler.API/Backends/SourceBackend.cs
- src/compiler/Uno.Compiler.Backends.CPlusPlus/CppBackend.cs
- src/compiler/Uno.Compiler.Core/Syntax/Builders/BundleBuilder.cs
- src/compiler/Uno.Compiler.Core/Syntax/Macros/MacroExpander.cs
This improves subsequent builds by avoiding unnecessary changes and generates less C++ source files.
> C++ build improvements

- lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml
- lib/UnoCore/Targets/Android/com/fuse/App.java
- lib/UnoCore/Targets/iOS/Uno-iOS/AppDelegate.mm
- lib/UnoCore/Targets/iOS/Uno-iOS/Context.h
- lib/UnoCore/Targets/iOS/Uno-iOS/Context.mm
https://developer.apple.com/ios/universal-links
https://developer.android.com/training/app-links
Todo: Add usage to Interapp docs
> Apple Universal Link & Android App Link Support via Interapp

- lib/UnoCore/Targets/Android/app/src/main/CMakeLists.txt
This fixes issues with paths and quoting in CMakeLists.
> Android: jni-lib path fixes

- lib/UnoCore/Targets/Android/@(Java.PackageDirectory)/@(Activity.Name).java
- lib/UnoCore/Targets/Android/Uno/Graphics/GLHelper.cpp
- lib/UnoCore/Targets/Android/Uno/Graphics/GLHelper.h
Fixes #194.
Kudos to @AndrewEQ for testing.
> Fix regression introduced in #162

- lib/FuseJS.Transpiler/src/package-lock.json
- lib/FuseJS.Transpiler/src/package.json
This will silence the security alert seen on GitHub.
>  FuseJS.Transpiler: fix security alert

- lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name).entitlements
- lib/UnoCore/Targets/iOS/iOS.uxl
> Fixed iPhone Xs Max launch image & Added Sign in with Apple Capability

- src/compiler/Uno.Compiler.Backends.CIL/Uno.Compiler.Backends.CIL.csproj
- src/compiler/Uno.Compiler.Backends.CIL/packages.config
- src/compiler/Uno.Compiler.Backends.Metadata/Uno.Compiler.Backends.Metadata.csproj
- src/compiler/Uno.Compiler.Backends.Metadata/packages.config
- src/compiler/Uno.Compiler.Backends.UnoDoc/Uno.Compiler.Backends.UnoDoc.csproj
- src/compiler/Uno.Compiler.Backends.UnoDoc/packages.config
- src/compiler/Uno.Compiler.Extensions/Uno.Compiler.Extensions.csproj
- src/compiler/Uno.Compiler.Extensions/packages.config
- src/disasm/Uno.Disasm-WPF/App.config
- src/disasm/Uno.Disasm-WPF/Uno.Disasm-WPF.csproj
- src/disasm/Uno.Disasm-WPF/packages.config
- src/disasm/Uno.Disasm/app.config
- src/engine/Uno.Build.Targets/app.config
- src/engine/Uno.Build/Uno.Build.csproj
- src/engine/Uno.Build/app.config
- src/engine/Uno.Build/packages.config
- src/engine/Uno.ProjectFormat/Uno.ProjectFormat.csproj
- src/engine/Uno.ProjectFormat/packages.config
- src/main/Uno.CLI.Main/App.config
- src/main/Uno.CLI/app.config
- src/testing/Uno.CompilerTestRunner/App.config
- src/testing/Uno.TestRunner.BasicTypes/app.config
- src/testing/Uno.TestRunner.CLI/App.config
- src/testing/Uno.TestRunner.Loggers/app.config
- src/testing/Uno.TestRunner.Tests/app.config
- src/testing/Uno.TestRunner/app.config
- src/ux/Uno.UX.Markup.UXIL/Tests/app.config
This upgrades NuGet dependencies to newest versions.
> Update nuget packages

- src/disasm/Uno.Disasm-WPF/MainWindow.xaml
- src/disasm/Uno.Disasm/BuildService.cs
- src/disasm/Uno.Disasm/ILView/Packages/BundleFileItem.cs
I was playing around with the old disassembly tool one day and did some tweaks in the process, and fixed compile-errors.
> Disasm UI tweaks

- lib/UnoCore/Targets/Native/build.sh
- lib/UnoCore/Targets/iOS/build.sh
Provide some friendly hints when required software is missing on the system.
> Detect required macOS software

- .unoconfig
- config/common.unoconfig
- scripts/pack.sh
- src/engine/Uno.Configuration/UnoConfig.cs
- src/main/Uno.CLI/Diagnostics/Config.cs
Some refactoring on config files and related code.
> Config-file clean-ups

- lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml
added config change to observe
> Android Q(29) - Dark Theme Support

- README.md
Move Contributing section so it comes right before Contributors section.
> README: move Contributing section

- src/common/Uno.Common/Diagnostics/Shell.cs
- src/common/Uno.Common/Logging/LogProfiler.cs
- src/common/Uno.Common/Logging/LogState.cs
- src/compiler/Uno.Compiler.Core/IL/Optimizing/ILStripper.cs
- src/engine/Uno.Build/ProjectBuilder.cs
- src/engine/Uno.Build/Stuff/Installer.cs
Various logging tweaks just to improve how things look a little bit.
> Subtle log tweaks

- README.md
- lib/UnoCore/Backends/CPlusPlus/CPlusPlus.uxl
- tests/src/UnoTest/General/Extern.uno
This enables C++14 features in foreign C++ code.
More info available on https://en.wikipedia.org/wiki/C++14
> Upgrade to C++14 standard

- lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml
- added declaration for app optimized for Android Go: https://developer.android.com/docs/quality-guidelines/building-for-billions-device-capacity#androidgo
> Android - Android Go Support

- lib/Uno.Permissions/Permissions.java
- lib/UnoCore/Targets/Android/@(Java.PackageDirectory)/@(Activity.Name).java
- lib/UnoCore/Targets/Android/Android.uxl
- lib/UnoCore/Targets/Android/Dependencies.uxl
- lib/UnoCore/Targets/Android/app/build.gradle
- lib/UnoCore/Targets/Android/com/fuse/Activity.java
- lib/UnoCore/Targets/Android/com/fuse/App.java
- lib/UnoCore/Targets/Android/gradle.properties
Migrated support libraries to AndroidX
https://developer.android.com/jetpack/androidx/migrate
> AndroidX Support

- package-lock.json
- package.json
This upgrades NPM packages to newest versions, containing bug-fixes.
> Upgrade NPM dependencies

- src/engine/Uno.Build.Targets/Android/AndroidBuild.cs
> Android Proguard Fix

- docs/command-line-reference.md
- package.json
- scripts/build.sh
- scripts/pack.sh
- src/common/Uno.Common/CLI/Command.cs
- src/common/Uno.Common/Logging/Log.cs
- src/engine/Uno.Build/BuildDriver.cs
- src/engine/Uno.Build/ProjectBuilder.cs
- src/main/Uno.CLI/Projects/BuildCommand.cs
A few improvements and tweaks related to logging and scripts.
> Various improvements

- lib/Uno.Data.Xml/Source/System.Xml.uno
- lib/Uno.Testing/Registry.uno
- src/compiler/Uno.Compiler.Backends.CIL/CilBackend.cs
- src/compiler/Uno.Compiler.Backends.CIL/CilTransform.cs
- src/compiler/Uno.Compiler.Core/IL/Validation/ILVerifier.cs
- src/compiler/Uno.Compiler.Core/Syntax/Builders/TypeBuilder.cs
- src/compiler/Uno.Compiler.Core/Syntax/Compilers/FunctionCompiler.cs
- src/ux/Uno.UX.Markup.CompilerReflection/CompilerReflection.cs
Some fixes and tweaks cherry-picked to prepare for upcoming compiler features.
> CIL fixes and tweaks

- lib/Uno.Permissions/AndroidPermissionsInternal.uno
- lib/Uno.Permissions/AndroidPermissionsInternal.uxl
- lib/Uno.Permissions/Permissions.uno
- lib/Uno.Permissions/Permissions.uxl
- lib/UnoCore/Targets/iOS/@(Project.Name)/@(Project.Name)-Info.plist
Required for https://github.com/fuse-open/fuselibs/pull/1344
> GeoLocation Upgrade

- lib/UnoCore/Targets/Android/Android.uxl
Updated default build tools version, compile version and target version
> SDK versions updated

- src/compiler/Uno.Compiler.Backends.CIL/Uno.Compiler.Backends.CIL.csproj
- src/compiler/Uno.Compiler.Backends.CIL/packages.config
- src/compiler/Uno.Compiler.Backends.Metadata/Uno.Compiler.Backends.Metadata.csproj
- src/compiler/Uno.Compiler.Backends.Metadata/packages.config
- src/compiler/Uno.Compiler.Backends.UnoDoc/Uno.Compiler.Backends.UnoDoc.csproj
- src/compiler/Uno.Compiler.Backends.UnoDoc/packages.config
- src/compiler/Uno.Compiler.Extensions/Uno.Compiler.Extensions.csproj
- src/compiler/Uno.Compiler.Extensions/packages.config
- src/disasm/Uno.Disasm-WPF/Uno.Disasm-WPF.csproj
- src/disasm/Uno.Disasm-WPF/packages.config
- src/engine/Uno.Build/Uno.Build.csproj
- src/engine/Uno.Build/packages.config
- src/engine/Uno.ProjectFormat/Uno.ProjectFormat.csproj
- src/engine/Uno.ProjectFormat/packages.config
- src/main/Uno.CLI/Uno.CLI.csproj
- src/main/Uno.CLI/packages.config
- src/runtime/Uno.AppLoader-WinForms/Uno.AppLoader-WinForms.csproj
- src/runtime/Uno.AppLoader-WinForms/packages.config
- src/runtime/Uno.Support.OpenTK/Uno.Support.OpenTK.csproj
- src/runtime/Uno.Support.OpenTK/packages.config
- src/testing/Uno.TestRunner.BasicTypes/Uno.TestRunner.BasicTypes.csproj
- src/testing/Uno.TestRunner.BasicTypes/packages.config
- src/testing/Uno.TestRunner.Tests/Uno.TestRunner.Tests.csproj
- src/testing/Uno.TestRunner.Tests/app.config
- src/testing/Uno.TestRunner.Tests/packages.config
- src/ux/Uno.UX.Markup.AST/Tests/Uno.UX.Markup.AST.Tests.csproj
- src/ux/Uno.UX.Markup.AST/Tests/packages.config
- src/ux/Uno.UX.Markup.UXIL/Tests/Uno.UX.Markup.UXIL.Tests.csproj
- src/ux/Uno.UX.Markup.UXIL/Tests/packages.config
This upgrades all NuGet packages to most recent versions.
> Upgrade NuGet packages

- scripts/find-msbuild.ps1
This adds support for building Uno solutions using Visual Studio 2019.
> Build using Visual Studio 2019 when available

- src/compiler/Uno.Compiler.API/Domain/Graphics/Block.cs
- src/compiler/Uno.Compiler.API/Domain/IL/IEntity.cs
- src/compiler/Uno.Compiler.API/Domain/IL/Members/Member.cs
- src/compiler/Uno.Compiler.API/Domain/IL/Members/Parameter.cs
- src/compiler/Uno.Compiler.API/Domain/IL/Namespace.cs
- src/compiler/Uno.Compiler.API/Domain/IL/Types/DataType.cs
- src/compiler/Uno.Compiler.Backends.CPlusPlus/CppPrecalc.cs
- src/compiler/Uno.Compiler.Core/IL/Optimizing/ILStripper.cs
This fixes a small bug in `ILStripper` and makes some code a little bit nicer.
> Compiler clean-ups

- lib/Uno.Graphics.Utils/Text/FontFaceSpriteFont.uno
- lib/Uno.Graphics.Utils/Text/TextRenderer.uno
- lib/UnoCore/Source/Uno/Collections/Dictionary.uno
- lib/UnoCore/Source/Uno/Collections/List.uno
- lib/UnoCore/Source/Uno/Color.uno
- lib/UnoCore/Source/Uno/Graphics/GraphicsController.uno
- lib/UnoCore/Source/Uno/IO/StreamReader.uno
- lib/UnoCore/Source/Uno/Matrix.uno
- lib/UnoCore/Source/Uno/Quaternion.uno
- lib/UnoCore/Source/Uno/Rect.uno
- lib/UnoCore/Source/Uno/Runtime/Implementation/Internal/NumericFormatter.uno
- lib/UnoCore/Source/Uno/String.uno
- lib/UnoCore/Source/Uno/Time/Calendars/GregorianYearMonthDayCalculator.uno
- lib/UnoCore/Source/Uno/Time/Calendars/YearMonthDayCalculator.uno
- lib/UnoCore/Source/Uno/Time/Text/PatternPart.uno
- lib/UnoCore/Source/Uno/Vector.uno
This adds `using` statements to replace repeating qualifiers in code using `Math`, `Matrix` or `Vector` classes. This makes our code slightly more compact and nice, subjectively.
> Math code clean-ups

- .appveyor.yml
- lib/UnoCore/Targets/Native/Native.uxl
- lib/UnoCore/prebuilt/uno-base.stuff
This upgrades C++ compilers and dependencies to use Visual Studio 2019 on Windows.
> Windows: upgrade C++ compilers

- docs/build-instructions.md
- docs/configuration.md
- lib/UnoCore/Targets/Native/Native.uxl
- lib/UnoCore/Targets/Native/build.bat
- lib/UnoCore/Targets/Native/run.bat
A few more fixes related to the recent upgrade to Visual Studio 2019.
> More Visual Studio 2019

- lib/UnoCore/Targets/iOS/Uno-iOS/AppDelegate.mm
This is to make silent Xcode warning
> iOS Fix app delegate method signature

- lib/UnoCore/Tests/Math.Test.uno
- src/test/runner/UnoTest.cs
- src/tool/cli/Projects/Test.cs
This fixes two regressions introduced in #322 and #337.
> Fix regressions

- .appveyor.yml
- .travis.yml
- lib/UnoCore/Source/Uno/Compiler/ExportTargetInterop/Foreign/ObjC/ObjC.cpp.uxl
- lib/UnoCore/Targets/Android/run.bat
- lib/UnoCore/Targets/Android/run.sh
- lib/UnoCore/Targets/Native/run.bat
- lib/UnoCore/Tests/Math.Test.uno
- package-lock.json
- package.json
- scripts/pack.sh
- scripts/restore.js
- src/runtime/mac/app-mac.csproj
- src/tool/engine/BuildDriver.cs
Another round of small patches for 2.0.
> Micro improvements

- lib/UnoCore/Targets/DotNet/Executable.uxl
- package-lock.json
- package.json
- src/runtime/mac/app-mac.csproj
- src/runtime/mac/packages.config
This upgrades Xamarin.Mac from version 3.4 to version 5.14.
> Xamarin.Mac v5.14

- .appveyor.yml
This sets up AppVeyor to build our code for Android.
> AppVeyor: Android build

- README.md
- lib/UnoCore/Backends/CPlusPlus/CPlusPlus.uxl
- lib/UnoCore/Targets/PInvoke/PInvoke.uxl
This enables C++17 features in Uno-apps.
> Upgrade to C++17 standard

- lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/HttpRequest.java
- lib/Uno.Net.Http/Implementation/Android/ExperimentalHttp/UploadTask.java
> See https://github.com/fuse-open/fuselibs/issues/1363.
We need to revert this commit temporarily so we can cut a working release.
Please note that this is not a problem at all, we will just cut another release once a proper fix has landed.
Thank you for your contributions.
> Fix regression

- lib/UnoCore/Backends/CPlusPlus/Uno/Uno.h
This fixes a regression #354 introduced in #349.
> UnoCore: use relative include path

- src/tool/engine/Adb/AdbDevice.cs
Output formatting in 'adb' has changed between versions and there is
no longer a newline before "Failure [...]", breaking our reinstall logic.
Also (IIRC), older versions of 'adb' always exited with code 0 regardless
of success or failure, being the reason we were scanning the output in
the first place.
Now I see that my modern version of 'adb' exits with non-zero code on
failure, so this patch updates the logic to check exit codes instead,
and also logs more details about uninstalling.
> LaunchApk: update reinstall logic

- src/common/Logging/Log.cs
- src/compiler/api/Backends/Backend.cs
- src/compiler/backend/cil/CilBackend.cs
- src/compiler/backend/unodoc/UnoDocBackend.cs
- src/tool/engine/BuildDriver.cs
Some tweaking to how things are being printed to log during build.
> Build log tweaks

- lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml
This makes it possible to control the hardware acceleration setting
on Android.
https://developer.android.com/guide/topics/graphics/hardware-accel
> Android: add HardwareAccelerated project property

- package-lock.json
- package.json
This upgrades xamarin-mac to version 8.8.0.
> upgrade xamarin-mac

- lib/UnoCore/Targets/Android/app/src/main/AndroidManifest.xml
Closes https://github.com/fuse-open/fuselibs/issues/1417
> Android: add RequestLegacyExternalStorage unoproj property

- src/disasm/core/BuildService.cs
- src/disasm/wpf/MainWindow.xaml.cs
This makes our rarely used disassembler compile again.
> Uno.Disasm: compile fixes

- lib/UnoCore/android/android.uxl
- lib/UnoCore/android/app/build.gradle
This adds two more UXL properties for build.gradle.
> Android: add Gradle.Dependency.{Debug, Release}Implementation

- lib/UnoCore/ios/@(Project.Name)/@(Project.Name)-Info.plist
this will silence the XCode console:
> Silent warning: no UIScene configuration dictionary

- .appveyor.yml
- package-lock.json
Use nodejs v16 on AppVeyor and upgrade package-lock.json to version 2.
> use nodejs v16

- src/common/Diagnostics/PlatformDetection.cs
> common: print arm archs in lower-case (beta-3.0)

- lib/Uno.Data.Xml/cpp/pugiconfig.hpp
- lib/Uno.Data.Xml/cpp/pugixml.cpp
- lib/Uno.Data.Xml/cpp/pugixml.hpp
- lib/Uno.Data.Xml/cpp/pugixml.uxl
This upgrades pugixml to the latest version, silencing compile time warnings seen when building using Xcode 14.
> Uno.Data.Xml: pugixml -> 1.13

- lib/UnoCore/UnoCore.unoproj
- src/common/Diagnostics/Shell.cs
- src/common/Logging/Log.cs
- src/compiler/api/Backends/Backend.cs
- src/compiler/api/Backends/BuildType.cs
- src/compiler/core/IL/Building/Entrypoint/MainClassFinder.cs
- src/compiler/core/IL/Optimizing/ILStripper.cs
- src/disasm/core/ILView/ILItemBuilder.cs
- src/tool/engine/Libraries/BundleCache.cs
- src/tool/engine/Libraries/LibraryProject.cs
- src/tool/engine/Targets/LibraryBuild.cs
- src/tool/engine/Targets/MetadataBuild.cs
- src/tool/engine/Targets/PInvokeBuild.cs
- src/tool/project/Project.cs
- src/tool/project/PropertyDefinitions.cs
> some small tweaks (beta-3.0)

- src/test/runner/Loggers/ConsoleLogger.cs
- src/test/runner/ProjectDiscoverer.cs
- src/test/runner/TestProjectRunner.cs
- src/test/runner/UnoTest.cs
This adds more newlines in the console output and in the source code, making things a little bit nicer.
> uno-test: more newlines (beta-3.0)

- src/disasm/core/BuildService.cs
- src/disasm/core/ILView/ILItemBuilder.cs
- src/disasm/core/Uno.Disasm.csproj
- src/disasm/wpf/App.xaml.cs
- src/disasm/wpf/disasm-wpf.csproj
The solution builds on .NET 6.0 now but some more work is required to make the app run properly again.
> disasm: fix-up .NET 6.0 solution (beta-3.0)

- lib/UnoCore/android/dependencies.uxl
> android: gradle-plugin -> 7.4.2

- .appveyor.yml
- package-lock.json
- package.json
- scripts/timeout.js
Sometimes we see something hanging when running tests on CI, and this commit makes the build terminate faster than waiting 60 mintues for AppVeyor to time out.
> kill tests after 15 minutes (beta-3.0)
